-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql312.epizy.com
-- Generation Time: Aug 21, 2020 at 03:36 AM
-- Server version: 5.6.48-88.0
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `epiz_25928170_products`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(200) CHARACTER SET utf16 COLLATE utf16_croatian_ci NOT NULL,
  `category_id` int(11) NOT NULL,
  `subcategory_id` int(11) NOT NULL,
  `description` text CHARACTER SET utf16 COLLATE utf16_croatian_ci NOT NULL,
  `url` varchar(200) CHARACTER SET utf16 COLLATE utf16_croatian_ci NOT NULL,
  `housing` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `power` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `gms` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `resources` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `parameter` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `inputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `outputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `cable` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `accessories` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `commodity` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `appliances` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `recomended` tinyint(4) DEFAULT NULL,
  `other` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_name` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_description` text CHARACTER SET utf16 COLLATE utf16_croatian_ci,
  `it_housing` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_power` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_gms` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_resources` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_parameter` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_inputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_outputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_cable` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_accessories` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_commodity` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_appliances` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `it_other` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_name` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_description` text CHARACTER SET utf16 COLLATE utf16_croatian_ci,
  `sr_housing` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_power` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_gms` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_resources` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_parameter` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_inputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_outputs` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_cable` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_accessories` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_commodity` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_appliances` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL,
  `sr_other` varchar(255) CHARACTER SET utf16 COLLATE utf16_croatian_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `category_id`, `subcategory_id`, `description`, `url`, `housing`, `power`, `gms`, `resources`, `parameter`, `inputs`, `outputs`, `cable`, `accessories`, `commodity`, `appliances`, `recomended`, `other`, `it_name`, `it_description`, `it_housing`, `it_power`, `it_gms`, `it_resources`, `it_parameter`, `it_inputs`, `it_outputs`, `it_cable`, `it_accessories`, `it_commodity`, `it_appliances`, `it_other`, `sr_name`, `sr_description`, `sr_housing`, `sr_power`, `sr_gms`, `sr_resources`, `sr_parameter`, `sr_inputs`, `sr_outputs`, `sr_cable`, `sr_accessories`, `sr_commodity`, `sr_appliances`, `sr_other`) VALUES
(16, 'LEK30', 5, 11, 'LEK30 is a 3 digits thermometer, panel mounted.\r\nA PTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 32 x 74 mm hole in the panel.\r\nSuitable for refrigeration or heating appliances, can accept the most common power supplies. ', 'lek30a.jpg', 'ABS plastic, self extinguishing, suitable for 32 x74 mm hole. Blocked with a plastic clamp.', 'Selectable between:|230Vac +/-10%, 50-60Hz| 115Vac +/-10%, 50-60Hz| 24Vac +/-10%, 50-60Hz| 12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=17mm          ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '', 'NTC sensor 10k', '', '', '', '', 'Cooling & heating to display the temperature of a cell or a liquid.', 0, NULL, 'LEK30', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'LEK30', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(18, 'LEK32', 5, 11, 'LEK32 is a 3 digits thermometer, panel mounted.\r\nAnalog input allows to display the most common variables: temperature, pressure etc.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel.\r\nSuitable for a wide range of appliances. ', 'lek32.jpg', 'ABS plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', '12Vac +/-10%, 50-60Hz| |', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion)', '', 'selectable between PTC, NTC, PT100, PT1000,  4-20mA (humidity , pressure)', 'two alarm relays 8A max (3A inductive)', '', '', '', 'Cooling, heating, pressure, humidity.', 0, NULL, 'LEK32', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'LEK32', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(17, 'LEK31', 5, 11, 'LEK31 is a 3 digits thermometer, panel mounted.\r\nA PTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel.\r\nSuitable for refrigeration or heating appliances, can accept the most common power supplies. ', 'lek31.jpg', 'ABS plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '', 'PTC sensor KTY 88', 'alarm relay 8A max (3 inductive)', '', '', '', 'Cooling & heating to display any temperature.', 0, NULL, 'LEK31', '', NULL, '', '', '', '', '', '', '', '', '', '', NULL, 'LEK31', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(36, 'REK33CHT', 5, 9, 'REK33CHT is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C. Assembled inside a housing suitable for 29 x 68 mm hole in the panel. A set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp. It can accept the most common power supplies. It contains a Real Time Clock, so defrost starts can be set with accuracy. Use of capacitive pushbuttons, so that no mechanical parts are present..A special parameter allows to drive a printer for HACCP purposes. ', 'rek33cht-a.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', 'Real Time Clock;                       HACCP;                       Capacitive switches', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, 'REK33CHT', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33CHT', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(10, 'LEK21', 5, 11, 'LEK21 is a 3 digits thermometer, panel mounted.\r\nA PTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 31 x 64 mm hole in the panel.\r\nSuitable for refrigeration or heating appliances, can accept the most common power supplies. ', 'lek21a.jpg', ' ABS plastic, self extinguishing, suitable for 31 x 64 mm hole panel. Blocked with a plastic clamp.', 'Selectable between:| 230Vac +/-10%, 50-60Hz | 115Vac +/-10%, 50-60Hz | 24Vac +/-10%, 50-60Hz | 12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=17mm   ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '', 'PTC sensor KTY 88', 'one relay 8A (3A inductive)', '', '', '', 'Cooling & heating to display any temperature.', 0, NULL, 'LEK21', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'LEK21', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(23, 'REK31', 5, 9, 'REK31 is a digital controller with 3 digits display, panel mounted, for cooling applications.\r\nA PTC or NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a 4 DIN modules housing suitable for an omega clamp. A power set of parameters allows the action for cooling or heating.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost of cooling systems up to 1/2 Hp. It can accept the most common power supplies. ', 'rek31a.jpg', 'ABS plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '19 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'one relay 15A (5A inductive)', '', '', '', 'Small cooling systems, where defrost is obtained switching off the compressor.', 0, NULL, 'REK31', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(22, 'TEK41', 5, 11, 'TEK41 is a digital thermostat with 3 digits display, panel mounted, both for cooling and heating applications.\r\nA PTC or NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a 4 DIN modules housing suitable for an omega clamp. A power set of parameters allows the action for cooling or heating.\r\nIt can accept the most common power supplies. ', 'tek41aa.jpg', '4 DIN modules, suitable for an omega clamp', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=17mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '11 parameters', 'PTC KTY81-121 or NTC 10K sensor ', 'one relay 8A (3A inductive)', '', '', '', 'Heating or cooling systems, working between –50 and +90°C .', 0, NULL, 'TEK41', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'TEK41', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(24, 'REK31E', 5, 9, 'REK31E is a digital controller with 3 digits display, panel mounted, for cooling applications. A PTC or NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3 Hp. It can accept the most common power supplies. ', 'rek31e-a.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: cycled by time, stopping the compressor', '20 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'one relay 8A (3A inductive)', '', '', '', 'Cooling systems, where defrost is obtained switching off the compressor .', 0, NULL, 'REK31E', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31E', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(25, 'REK31EA', 5, 9, 'REK31EA is a digital controller with 3 digits display, back panel mounted, for cooling applications.\r\nOne NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C for cell. Assembled into an open board, it is suitable for back panel solutions. A fixed set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3HP. The setpoint can be changed by a knob. Suitable for small applications. It can accept the most common power supplies. ', 'rek31ea-a.jpg', 'Open board, need to be installed inside a panel.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', 'fixed internally', 'NTC 10K for cell', 'one relay 8A (3A inductive)', '', '', '', 'Small cooling systems, where defrost is obtained switching off the compressor.', 0, NULL, 'REK31EA', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31EA', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(26, 'REK31ED', 5, 9, 'REK31ED is a digital controller with 3 digits display, panel mounted, for cooling applications.\r\nTwo PTC or NTC sensor allow very accurate measurements of a temperature between –50 and + 90 °C, both for cell and evaporator.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3 Hp. It can accept the most common power supplies. ', 'rek31ed.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: cycled by time, stopping the compressor, controller by the evaporator sensor', '24 parameters', 'PTC sensor KTY120 or NTC 10K for cell and evaporator', 'one relay 8A (3A inductive)', '', '', '', 'Cooling systems, where defrost is obtained stopping the compressor.', 0, NULL, 'REK31ED', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31ED', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(27, 'REK31EE', 5, 9, 'REK31EE is a digital controller with 3 digits display, panel mounted, for cooling applications.\r\nOne NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C for cell. Assembled inside a housing suitable for 29 x 68 mm hole in the panel. A short set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3HP. Suitable for small applications.\r\nIt can accept the most common power supplies.', 'rek31ee.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: cycled by time, stopping the compressor', '8 parameters', 'NTC 10K for cell', 'one relay 8A (3A inductive)', '', '', '', 'Small cooling systems, where defrost is obtained switching off the compressor.', 0, NULL, 'REK31EE', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31EE', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(28, 'REK31ET', 5, 9, 'REK31ET is a digital controller with 3 digits display, panel mounted, for cooling applications. A PTC or NTC sensor allows very accurate measurements of temperatures between –50 and + 90 °C. Assembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3 Hp. It can accept the most common power supplies. Use of capacitive pushbuttons, so no mechanical parts are involved.', 'rek31et.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14 mm 	        	ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: cycled by time, stopping the compressor', '19 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'one relay 8A (3A inductive)', '', '', 'PUSHBUTTONS: capacitive types', 'Cooling systems, where defrost is obtained switching off the compressor.', 0, NULL, 'REK31ET', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31ET', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(29, 'REK31ETH', 5, 9, 'REK31ETH is a digital controller with 3 digits display, panel mounted, for cooling applications. A PTC or NTC sensor allows very accurate measurements of a temperature between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost of cooling systems up to 1/3 Hp. It can accept the most common power supplies. The switches use the capacitive method, so no mechanical parts are involved. A special parameter allows to drive a printer for HACCP purposes. ', 'rek31eth.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14 mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: cycled by time, stopping the compressor', '19 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'one relay 8A (3A inductive)', '', '', 'PUSHBUTTONS: capacitive types 		HACCP: Using parameters n. 28, the controller drives a printer', 'Cooling systems, where defrost is obtained switching off the compressor.', 0, NULL, 'REK31ETH', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK31ETH', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(30, 'REK32', 5, 9, 'REK32 is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost outputs of cooling systems up to 1/3 Hp. It can accept the most common power supplies. ', 'rek32.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor', '26 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'the compressor: one relay 8A (3A inductive); Defrost: one relay 5A resistive', '', '', '', 'Cooling systems, where defrost must be fast.', 0, NULL, 'REK32', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK32', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(31, 'REK32T', 5, 9, 'REK32T is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor and defrost outputs of cooling systems up to 1/3 Hp. It can accept the most common power supplies.\r\nUse of capacitive pushbuttons, so no mechanical parts are present. ', 'rek32t.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '26 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'the compressor: one relay 8A (3A inductive); Defrost: one relay 5A resistive', '', '', 'PUSHBUTTONS: capacitive types', 'Cooling systems, where defrost must be fast.', 0, NULL, 'REK32T', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK32T', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(32, 'REK32TH', 5, 9, 'REK32TH is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nA power set of parameters allows the control of the compressor and defrost outputs of cooling systems up to 1/3 Hp. It can accept the most common power supplies.\r\nUse of capacitive pushbuttons, so no mechanical parts are present.\r\nA special parameter allows to drive a printer for HACCP purposes. ', 'rek32th.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '26 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'the compressor: one relay 8A (3A inductive); Defrost: one relay 5A resistive', '', '', 'PUSHBUTTONS: capacitive types 		 HACCP: Using parameters n. 28, the controller drives a printer.', 'Cooling systems, where defrost must be fast.', 0, NULL, 'REK32TH', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK32TH', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(33, 'REK33', 5, 9, 'REK33 is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel.\r\nA power set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp.\r\nIt can accept the most common power supplies. \r\n', 'rek33.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', '', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, 'REK33', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(34, 'REK33C', 5, 9, 'REK33C is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp. It can accept the most common power supplies. It contains a Real Time Clock, so defrost starts can be set with accuracy. ', 'rek33c.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', 'Real Time Clock', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33C', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(35, 'REK33CH', 5, 9, 'REK33CH is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp. It can accept the most common power supplies. A special parameter allows to drive a printer for HACCP purposes.\r\nIt contains a Real Time Clock, so defrost starts can be set with accuracy. ', 'rek33ch.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', 'Real Time Clock;                        HACCP', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, 'REK33CH', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33CH', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(37, 'REK33H', 5, 9, 'REK33H is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of temperature between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp. It can accept the most common power supplies. A special parameter allows to drive a printer for HACCP purposes.', 'rek33h.jpg', 'ABS plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', 'HACCP', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, 'REK33H', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33H', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(38, 'REK33TC', 5, 9, 'REK33TC is a digital controller with 3 digits display, panel mounted, for cooling applications. Two PTC or NTC sensors allow very accurate measurements of a temperature between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 29 x 68 mm hole in the panel. A power set of parameters allows the control of the compressor, defrost and fan outputs for a cooling systems up to 1/2 Hp. It can accept the most common power supplies. It contains a Real Time Clock, so defrost starts can be set with accuracy. The switches use the capacitive method, so that no mechanical parts are present.', 'rek33tc.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel.). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		DEFROST: Cycled by time, by resistor or inverse cycle, stop by evaporator sensor.', '34 parameters', 'PTC sensor KTY120 or NTC 10K for cell', 'Compressor: one relay 15A (5A inductive); Defrost: one relay 5A resistive; Fan: one relay 5A resistive', '', '', 'Real Time Clock;                        Capacitive switches', 'Cooling systems, where defrost must be fast and the cell must be ventilated.', 0, NULL, 'REK33TC', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK33TC', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(39, 'REK64', 5, 9, 'REK64 is a digital controller with 4 digits display, panel mounted, for cooling applications. Three PTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C.\r\nAssembled inside a housing suitable for 30 x 150 mm hole in the panel. A power set of parameters allows the control of the compressor, defrost, fan, cabinet internal light outputs for a cooling systems up to 1 Hp. It can accept the most common power supplies. One internal buzzer gives an acoustic warning in case of alarm. It contains a Real Time Clock, so defrost starts can be set with accuracy. The third sensor can help the filter maintenance. ', 'nemaslike.jpg', 'Blue plastic panel 44 x 188 mm, suitable for 30 x 155 mm hole panel. Blocked with two screws from the front panel.', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 4 red LEDs digits, h=14mm                     ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 	        DEFROST: up to 6 cycles set by clock, using resistor or cycle inversion', '55 parameters', 'PTC sensor KTY120 for cell, defrost, filter', 'relay 30A (8A inductive) for the compressor 		relay 10A (8A inductive) for defrost 		relay 8A (8A inductive) for fan 		relay 8A (8A inductive) for cabinet internal light', 'on demand', '', 'via RS484 bus, EK protocol', 'Cooling systems, when sofisticated control are required.', 0, NULL, 'REK64', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK64', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(40, 'REK65', 5, 9, 'REK65 is a digital controller with 4 digits display, panel mounted, for cooling applications. Three PTC sensors allow very accurate measurements of temperatures between –50 and + 90 °C. Assembled inside a housing suitable for 30 x 150 mm hole in the panel. A set of parameters allows the control of the compressor, defrost, fan, cabinet internal light, alarm and ON/OFF outputs for a cooling systems up to 1 Hp. It can accept the most common power supplies. One internal buzzer gives an acoustic warning in case of alarms. It contains a Real Time Clock, so defrost starts can be set with accuracy. The third sensor can advise for the filter maintenance. ', 'nemaslike.jpg', 'Blue plastic panel 44 x 188 mm, suitable for 30 x 155 mm hole panel. Blocked with two screws from the front panel.', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz | 		12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 4 red LEDs digits, h=14 mm                     ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 	        DEFROST: up to 6 cycles set by clock, using resistor or cycle inversion', '55 parameters', 'PTC sensor KTY120 for cell, defrost, filter', 'relay 30A (8A inductive) for the compressor 		relay 10A (8A inductive) for defrost 		relay 8A (8A inductive) for fan 		relay 8A (8A inductive) for cabinet internal light 		relay 8A (8A inductive) for alarm 		relay 8A (8A inductive) for ON/OFF', 'on demand', '', 'via RS485 bus', 'Cooling systems, when sofisticated control are required.', 0, NULL, 'REK65', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'REK65', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(41, 'OMD/02/GLA', 6, 8, 'OMD/02/GLA is a two-way GSM mobile telephone communication device for applications in lifts, easy and quick to install. It complies with Dispositions 95/16/CE and Safety Regulation EN81-1/2 EN 81-70 EN81-28—CE compliants. Besides it has an IMQ mark and it is approved by Telecom Italia – TIM and is in compliance with the Privacy Laws. Its use is recommended in new lift applications but also for conforming old lifts to the latest safety rules. ', 'nemaslike.jpg', 'metal box dim. 160 x 175 x 60 mm, blue coloured', 'selectable between:| 230Vac +/-10%, 50-60Hz||', 'Siemens TC63I or TELIT GM 865', '1 loudspeaker inside the housing - 3 microphone ( housing - cabin - service box) - 5 Pushbuttons : 2 in the housing, not powered, N.C. (alarm start & end), 2 in the cabin, not powered, N.C. (alarm start & end), 1 in the service box. - 2 LEDS : one green, ', 'locally using the RS232 serial port or via remote SMS text messages over the mobile phone or Call Center software', '1 digital filter for alarm', '1 analog connection to the machine room via interphone', '', 'no accessories are foreseen', 'Call Center hardware and software.', 'new lifts or for old lifts conformity', 0, NULL, 'OMD/02/GLA', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'OMD/02/GLA', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(42, 'OMD/03/GLA', 6, 8, 'OMD/03/GLA is a two-way GSM mobile telephone communication device for applications in lifts, easy and quick to install. It complies with Dispositions 95/16/CE and Safety Regulation EN81-1/2 EN 81-70 EN81-28—CE compliants . Besides it has an IMQ mark and it is approved by Telecom Italia – TIM and is in compliance with the Privacy Laws. Its use is recommended in new lift applications but also for conforming old lifts to the latest safety rules.', 'nemaslike.jpg', 'metal box dim. 160 x 175 x 60 mm, blue coloured', 'selectable between:| 230Vac +/-10%, 50-60Hz||', 'Siemens TC63I or TELIT GM 865', '1 loudspeaker inside the housing - 3 microphone ( housing - cabin - service box) - 5 Pushbuttons : 2 in the housing, not powered, N.C. (alarm start & end), 2 in the cabin, not powered, N.C. (alarm start & end), 1 in the service box. - 2 LEDS : one green, ', 'locally using the RS232 serial port or via remote SMS text messages over the mobile phone or Call Center software', '1 digital filter for alarm', '1 analog connection to the machine room via interphone', 'one cable to the cabin for LEDs, microphone and switches - one cable to the service box - one cable for alarm digital filter', 'no accessories are foreseen', 'Call Center hardware and software', 'new lifts or for old lifts conformity', 0, NULL, 'OMD/03/GLA', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'OMD/03/GLA', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(43, 'DEK20', 3, 13, 'Wall mounting, endearing look with a protection cover, heating thermostat, battery powered, with daily settable clock. The Comfort and Economy daily period can be set through 6 x 24 clamps corresponding to 10 minutes each. ', 'dek100a.jpg', 'plastic housing with cover ', 'Battery 2 x 1,5 AA type -  1 year autonomy|||', '', 'Set points: two, independently settable 		Range: 10 - 30 °C 		Accuracy: +/- 1°C', '', 'on board NTC 10K sensor', ' one normally closed Relay switch, 230V 10A', '', '', '', 'domestic heating ', 0, NULL, 'DEK20', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK20', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(44, 'DEK01', 3, 13, 'DEK01 is a simple open board that can be inserted into the fan coil. It can switch ON and OFF the fan coil and select one of the three speeds of the fan. All the connections are Fast On. \r\n', 'dek01a.jpg', 'no housing, to be fixed in the fan coil', 'Selectable between:| 230Vac +/-10%, 50-60Hz| 115Vac +/-10%, 50-60Hz', '', '', '', '', '230 Vac 3A switch', 'on demand', '', '', 'only fan control', 0, NULL, 'DEK01', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK01', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(45, 'DEK02', 3, 13, 'DEK02 is a simple open board thermostat that can be inserted in the fan coil. With two switches the operator can select between winter and summer mode and the speed of the fan. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C. The fan can be enabled by an external thermostat to prevent the cold air circulation during winter. Supplied with a temperature sensor. ', 'dek02a.jpg', 'no housing , must be fixed on fan coil', '230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz', '', 'SETPOINT RANGE: 10-30°C 		SENSOR ACCURACY: +/- 1°C 		TERMINALS: faston 		CONTROL ALGORITHM: ON-OFF', '', 'TEMPERATURE SENSOR: NTC 10K', 'relay 230Vac, 3A', 'on demand', '', '', '2 pipes or only fan systems', 0, NULL, 'DEK02', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK02', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(46, 'DEK03AC', 3, 13, 'DEK03AC is a single housing microprocessor thermostat that can be installed in the fan coil or placed on the wall. It must be used with the fan equipped with AC motors  With one selector the user can the select the speed of the fan. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C or turn off the thermostat. The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a internal temperature sensor. ', 'nemaslike.jpg', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz|||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF algorithm                         1-2-3 speed selection', 'by 5 dispswitches', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'one 3 Amp relay for fan 		two 0,8A ,230Vac triacs for valves', 'on demand', 'temperature sensors NTC10K ', '', '2 pipes or 4 pipes only fan systems', 0, NULL, 'DEK03AC', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK03AC', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(47, 'DEK03EC', 3, 13, 'DEK03EC is a single housing microprocessor thermostat that can be installed in the fan coil or placed on the wall. It must be used with the fan equipped with EC motors.  With one selector the user can the select the speed of the fan. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C or turn off the thermostat. The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a internal temperature sensor. ', 'nemaslike.jpg', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz |||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF algorithm                         AUTO -1-2-3 speed selection', 'by 5 dispswitches', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'one 0-10V , 1mA for EC type fan 		two 0,8A ,230Vac triacs for valves', 'on demand', 'temperature sensors NTC10K ', '', '2 pipes or 4 pipes only fan systems for EC motor equipped fan coil', 0, NULL, 'DEK03EC', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK03EC', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(48, 'DEK04', 3, 13, ' DEK04 is a single housing microprocessor thermostat that can be installed in the fan coil or placed on the wall. It must be used with the fan equipped with AC motors  With one selector the user can the select the speed of the fan and turn OFF it . With a potentiometer, the user can set the temperature setpoint between 10 and 30°C . The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a internal temperature sensor. ', 'dek04a.jpg', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz|||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF algorithm                         Auto 1-2-3 speed selection', '', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'hree 230Vac,1A  triacs for AC type fan 		two 0,5A ,230Vac triacs for valves', 'on demand', 'temperature sensors NTC10K ', '', '2 pipes  / only fan systems', 0, NULL, 'DEK04', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK04', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(49, 'DEK05', 3, 13, 'DEK05 is a single housing microprocessor based thermostat that can be installed in the fan coil or placed on the wall. With one selector the user can switch ON the thermostat and select the speed of the fan or select the Auto mode. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C. With two push buttons the user can select between winter & summer operation or the comfort - economy mode. The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a temperature sensor. A complete parameters set allows to configure the thermostat for a wide range of applications. ', 'dek05a.jpg', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz|||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF or PWM algorithm                         Auto 1-2-3 speed selection                         Up to 10 parameters programmable with buttons sequence', 'up to 21 parameters', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'three 230Vac,1A  triacs for AC type fan 		two 0,5A ,230Vac triacs for valves                         one 230Vac,1A  triacs electrical heater', 'on demand', 'temperature sensors NTC10K ', 'ttl port for comunication', '2 pipes, 4 pipes, only fan, 2 pipes+elec. heater systems', 0, NULL, 'DEK05', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK05', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(50, 'DEK06', 3, 13, 'DEK06 is a microprocessor based thermostat that can be installed in the fan coil or placed on a panel. It can operate with or without the user interface and easily connected to a centralized control system using the RS485 serial port.\r\nIt can also works with the room units coded DEK09-10-11-12.\r\nIt can operate as master or as slave of a simple local network or of a more complex network.\r\nA complete parameters set allows to configure the thermostat for a wide range of applications. Thanks to a bootloader software features, the operating program can be easily changed using the network. ', 'dek06a.jpg', 'plastic housing V0 fire protection 8 modules DIN RAIL mounting ', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF, PWM,thermal, 2 stages, 0-10V                         Auto 1-2-3 speed selection', 'wide parameter range', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy 		one digital for summer/winter changeover', 'three 230Vac,1A  triacs for AC type fan 		two 0,5A ,230Vac triacs for valves                         one 230Vac,1A  triacs electrical heater', 'on demand', 'temperature sensors NTC10K ', 'RS 485 port plus LOCAL port', '2 pipes, 4 pipes, only fan, 2 pipes+elec. heater systems', 0, NULL, 'DEK06', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK06', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(51, 'DEK07', 3, 13, 'DEK07 is a microprocessor based VAV controller that can be installed near the cassette or in a panel. It can operate with or without the user interface and easily connected to a centralized control system using the RS485 serial port.\r\nIt can also works with all the room units coded DEK09-10-11-12. It can operate as master or as slave of a simple local network or of a more complex network.\r\nA complete parameters set allows to configure the thermostat for a wide range of applications. Thanks to a bootloader software features, the operating program can be easily changed using the network. \r\n', 'dek07a.jpg', 'plastic housing V0 fire protection 8 modules DIN RAIL mounting ', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		5 sequences algorithms', 'wide parameter range', 'one sensor NTC 10K for remote temperature 		2 air flow sensors ( 0-10V input)  		one digital input for remote ON/OFF 		one digital input for Economy 		one digital for summer/winter changeover or general purpose', 'one 0,5A ,230Vac triac for  heating valve 	          one 0,5A ,230Vac triac for  air damper1 	          one 0,5A ,230Vac triac for  air damper2                       one 230Vac,1A  triac for auxiliary output', 'on demand', 'temperature sensors NTC10K ', 'RS 485 port plus LOCAL port', 'VAV systems', 0, NULL, 'DEK07', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK07', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(52, 'DEK08', 3, 13, 'DEK08 is a general purpose I/O module, industrialized inside a 8 modules DIN RAIL housing. It has 8 digital or analog inputs and 8 relay outputs. Connected to the RS485 network, using a Modbus protocol, it can read the analog or digital inputs, compare them with the set limits and drive the relay according with the parameter set, programmed via the RS485 bus.\r\nIt can be used to drive alarm devices, lights and all the applications useful in an automated building. ', 'dek08a.jpg', 'plastic housing V0 fire protection 8 modules DIN RAIL mounting ', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz', '', 'CONTROL ALGORITHM TYPE ON/OFF                    	SENSOR ACCURACY: +/- 1°C', 'wide parameter range ', 'n°8 0-10V analog inputs 		n°6 free voltage digital inputs', ' n°8 relays, 1.5A max', 'on demand', '', 'RS 485 port ', 'UTA controls', 0, NULL, 'DEK08', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK08', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(53, 'DEK09', 3, 13, 'DEK09 is a room unit that can be fixed to the wall and connected to the DEK06 or DEK07, via 2 wires. It is equipped with a dial for the temperature setpoint, a dial for switch On the thermostat or select the fan speed, 2 push buttons for selecting the winter-summer operation or the confort  – economy - standby mode. One bicolour LED and one mono colour LED shows the status of the thermostat.', 'dek09a.jpg', 'plastic housing V0 fire protection ', 'via 2 wires from DEK06 or DEK07|||', '', 'Dial for temperature setting 		 Dial for fan speed selection 		one bicolour LED  		one monocolour LED', '', '', '', 'on demand', '', '', 'as room unit or remote sensor for DEK06 or DEK07 in fan coil systems', 0, NULL, 'DEK09', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK09', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(54, 'DEK10', 3, 13, 'DEK10 is a room unit that can be fixed to the wall and connected to the DEK06 or DEK07, via 2 wires. It is equipped with a monochrome LCD and 3 push buttons. Using the push buttons, the user can move through the icons on the display and select the temperature setpoint, the fan speed, the winter-summer operation, the confort – economy - standby mode. In the same way the user can also enter new parameter values. ', 'nemaslike.jpg', 'plastic housing V0 fire protection ', 'via 2 wires from DEK06 or DEK07|||', '', 'Monochrome LCD display  		 3 pushbuttons for menù navigation', '', '', '', 'on demand', '', '', 'as room unit or remote sensor for DEK06 or DEK07 in fan coil systems', 0, NULL, 'DEK10', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK10', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(55, 'DEK11', 3, 13, 'DEK11 is a flush mounting room unit that can be installed on the wall and connected to the DEK06 or DEK07, via 2 wires. It presents to the user a dial for the temperature setpoint, a dial for swtch On the thermostat or select the fan speed, 2 push buttons for selecting the winter-summer operation or the confort – economy - standby mode. One bicolour LED and one monocolour LED shows the status of the thermostat. ', 'dek11_b_c-a.jpg', 'plastic housing V0 fire protection, flush mounting type', 'via 2 wires from DEK06 or DEK07|||', '', 'Dial for temperature setting 		 Dial for fan speed selection 		one bicolour LED  		one monocolour LED', '', '', '', 'on demand', 'most common commercial frames ', '', 'as room unit or remote sensor for DEK06 or DEK07 in fan coil systems', 0, NULL, 'DEK11', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK11', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(56, 'DEK12', 3, 13, 'DEK12 is a flush in room unit that can be installed on the wall and connected to the DEK06 or DEK07, via 2 wires. It is equipped with a monochrome LCD and 3 push buttons. Using the push buttons, the user can move through the icons on the display and select the temperature setpoint, the fan speed, the winter-summer operation, the confort – economy - standby mode. In the same way the user can also enter new parameter values. The most common frames can be applicable to the housing. ', 'dek12_b_c-a.jpg', 'plastic housing V0 fire protection, flush mounting type', 'via 2 wires from DEK06 or DEK07|||', '', 'one LCD display 		 3 push buttons ', '', '', '', 'on demand', '', '', 'as room unit or remote sensor for DEK06 or DEK07 in fan coil systems', 0, NULL, 'DEK12', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK12', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(57, 'DEK13', 3, 13, 'DEK13 is a very powerful controller, microprocessor based. Mainly it can be used in central water production and distribution to manage the domestic hot water. Industrialized inside a 8 modules DIN RAIL housing, it has a local alphanumeric display, but can also drive an external touch screen display (DEK14).\r\nIt can be also connected via RS485 port to the network, and has a USB port for programming. A very large set of parameters, allows to be applicable in most heating applications (10 different applications).', 'dek13.png', 'plastic housing ,V0 fire protection, 8 modules DIN RAIL type', '230 Vac +/-10%, 50,60Hz|||', '', '10 different applications and parameters set  for the most common domestic clima and water regulation', 'wide range of parameters', 'six NTC 10K sensors 	two free voltages contacts, one pulse input for energy metering', 'N°2 relays 8A max ( 3 inductive),                N°8 triac s (0.4A max)                N°4 0-10V modulating', 'on demand', 'NTC 10K sensors', 'USB PORT: for data logging.                       N° 2 RS 485 ports, one for display, one for network', 'clima, domestic water and energy metering systems ', 0, NULL, 'DEK13', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK13', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(58, 'DEK14', 3, 13, 'DEK14 is a room unit that can be fixed on the wall and connected to the DEK13, via a RS485 port with 4 wires. It is a colour LCD, with the touchscreen feature. Touching the screen, the user can move through the menù and select the desired values and way of operation. ', 'dek14.png', 'plastic housing ,V0 fire protection, 8 modules DIN RAIL type', '5V via the connection to DEK13|||', '', '4,3 inches touch screen display  ', '', '', '', 'on demand', '', '', ' in connection with DEK13 as user interface', 0, NULL, 'DEK14', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK14', '', '', '', '', '', '', '', '', '', '', '', '', NULL);
INSERT INTO `products` (`id`, `name`, `category_id`, `subcategory_id`, `description`, `url`, `housing`, `power`, `gms`, `resources`, `parameter`, `inputs`, `outputs`, `cable`, `accessories`, `commodity`, `appliances`, `recomended`, `other`, `it_name`, `it_description`, `it_housing`, `it_power`, `it_gms`, `it_resources`, `it_parameter`, `it_inputs`, `it_outputs`, `it_cable`, `it_accessories`, `it_commodity`, `it_appliances`, `it_other`, `sr_name`, `sr_description`, `sr_housing`, `sr_power`, `sr_gms`, `sr_resources`, `sr_parameter`, `sr_inputs`, `sr_outputs`, `sr_cable`, `sr_accessories`, `sr_commodity`, `sr_appliances`, `sr_other`) VALUES
(59, 'DEK19', 3, 13, 'DEK19 is a single housing microprocessor based thermostat that can be installed in the fan coil or placed on the wall. With one selector the user can switch ON the thermostat and select the speed of the fan or select the Auto mode. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C. With two push buttons the user can select between winter & summer operation or the comfort - economy mode. The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a temperature sensor. A complete parameters set allows to configure the thermostat for a wide range of applications.', 'download.png', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz|||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF or PWM algorithm                         Auto 1-2-3 speed selection                         Mode Push button                         Summer Winter change o', '29 parameters', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'three 230Vac,1A  triacs for AC type fan 		two 0,5A ,230Vac triacs for valves                         one 0-10V DC, 1mA for EC type fan         ', 'on demand', 'temperature sensors NTC10K ', ' ttl port for comunication', '2 pipes, 4 pipes, only fan, 2 pipes+electrical heater, floor + fan coil, 2 pipe water heating/cooling + electrical heating ', 0, NULL, 'DEK19', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK19', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(60, 'DEK29', 3, 13, 'DEK29 is a single housing microprocessor based thermostat that can be installed in the fan coil or placed on the wall. With one selector the user can switch ON the thermostat and select the speed of the fan or select the Auto mode. With a potentiometer, the user can set the temperature setpoint between 10 and 30°C. With two push buttons the user can select between winter & summer operation or the comfort - economy mode. The fan can be enabled by an external thermostat or NTC sensor to prevent the cold air circulation during winter. Supplied with a temperature sensor. A complete parameters set allows to configure the thermostat for a wide range of applications. ', 'download.png', 'plastic housing V0 fire protection', '230Vac +/-10%, 50-60Hz|||', '', 'SETPOINT RANGE: 10-30°C                    	SENSOR ACCURACY: +/- 1°C 		Proportional-Integral ON-OFF or PWM algorithm                         Auto 1-2-3 speed selection                                                  Mode Push button                      ', '38 parameters', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', 'three 230Vac,1A  triacs for AC type fan 		two 0,5A, 230Vac triacs for valves                         one 0-10V DC, 1mA for EC type fan     ', 'on demand', 'temperature sensors NTC10K ', 'RS485 port with ModBus protocol up to 31 units (can be extended with internal parameter)', '2 pipes, 4 pipes, only fan, 2 pipes+electrical heater, floor + fan coil, 2 pipe water heating/cooling + electrical heating ', 0, NULL, 'DEK29', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK29', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(61, 'DEK50', 3, 13, 'DEK50 is a microprocessor based thermostat that can be installed in the fan coil or placed on the wall and used as single housing  flush mounting or dual housing wall mounting. Equipped with a back lighted LCD and four capacitive switches offer the user the possibility to change setpoint, mode, fan speed as well as to program the internal parameters. Supplied with a temperature sensor. A powerful range of parameters set allows to configure the thermostat for a wide range of applications.  ', 'download.png', 'plastic housing V0 fire protection, with or without a 4 modules DIN RAIL ', 'selectable between:| 		230Vac +/-10%, 50-60Hz | 		115Vac +/-10%, 50-60Hz | 		24Vac +/-10%, 50-60Hz', '', 'LCD back lighted display with up to 50 icons                      SETPOINT RANGE: 10-30°C                      SENSOR ACCURACY: +/- 1°C 	          Proportional-Integral ON-OFF or PWM algorithm                         Auto 1-2-3 speed selection            ', '49 parameters', 'one sensor NTC 10K for remote temperature 		one sensor NTC 10K for summer/winter changeover  		one digital input for remote ON/OFF 		one digital input for Economy', ' three 230Vac,1A  triacs for AC type fan 		two (four) 0,5A ,230Vac triacs for valves                         one 230Vac,1A  triacs for electrical heater                         one 0-10V DC, 1mA for EC type fan        ', 'on demand', 'temperature sensors NTC10K ', 'RS485 port with ModBus protocol up to 99 units                     Real Time Clock for weekly program                      CO2 measurement   The controller can be supplied in flush mounting version  or  wall mounting display and 4 modules DIN RAIL mountin', ' 2 pipes, 4 pipes, only fan, 2 pipes + electrical heater, floor + fan coil, 2 pipe water heating/cooling + electrical heating ', 0, NULL, 'DEK50', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEK50', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(91, 'DEW821', 1, 2, 'DEW821 is a filter monitor for improving the control of a domestic water system. The operator can set the date for the next service and a warning is generated when the time expires. \r\nBesides, it monitors the status of the pump and when it fails one alarm is generated. A range of parameters can featuring the way of operation of the filter monitor. The housing is a 32 x 74 mm size (front panel), that can be easily fixed to the front panel of the unit. ', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '230 Vac +/-10%, 50-60 Hz|||', '', 'DISPLAY:105 red dots  4 push buttons for user operation                 	acoustic buzzer for alarm', '11 parameters', '', 'one relay 230Vac, for max. 5A pump                	one relays VFC type for pump alarm  		one relays VFC type for common alarm ', 'on demand', '', '', ' monitoring of water filter / pump in domestic application', 0, NULL, 'DEW821', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW821', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(88, 'DEW810', 1, 3, 'DEW810 is an expansion module that works in combination with DEW002 controller for an accurate and reliable control of a domestic water; the coonection is via a proprietary serial port. This module can works as controller of a degassing unit or, generally to expand the features of the DEW002. It can drive one or two pumps (in alternance or in parallel). It accepts the most common  pressure sensors . The housing is a 32 x 74 mm size (front panel), that can be easily fixed to the front panel of the unit. ', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, 8 modules DIN RAIL type', '230Vac +/-10%, 50-60Hz|||', '', 'ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '', 'one pressure input up to 10 Bars, 4-20 mA              one free voltage digital input for  liquid level (only type S)              one sensor for max. pump temperature alarm (only type M)', 'two relay 230Vac, for max. 5A pumps                	one relays VFC type for alarm or temperature', 'on demand', 'pressure sensors', '', 'control of small, medium and big pressurization units', 0, NULL, 'DEW810', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW810', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(84, 'DED704', 2, 5, 'DED704 is a controller for absorbtion  dryers; it drives four valves, two per column, in the proper logic to get the right sequence . It can work on time sequence or be equipped with a dewpoint sensor, 4-20 mA type in order to optimized the use of the two columns. One alarm output is present, as well as a digital input for remote ON/OFF and a serial RS485 port, implementing the ModBus protocol. A set of parameters can featuring the dryer. A 3 digit blue display and 4 capacitive switches give the user friendly interface.\r\n', 'nemaslike.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '230Vac +/-10%, 50-60Hz |||', '', 'DISPLAY: 3 blue LEDs digits, h=7mm  	       	 ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 		4 CAPACITIVE SWITCHES', '12 parameters', 'one digital input for remote ON/OFF 		one 4-20mA input for dewpoint', 'one triac 230Vac, 1A for left column Inlet 		one triac 230Vac, 1A for left column Purge 		one triac 230Vac, 1A for right column Inlet 		one triac 230Vac, 1A for right column Purge', 'on demand', '', 'RS485 port with ModBus protocol', '2 columns absorbtion dryers', 0, NULL, 'DED704', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED704', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(85, 'DED705', 2, 5, 'DED705 is a controller for absorbtion  dryers; it drives four valves, two per column, in the proper logic to get the right sequence. It can work on time sequence or be equipped with a dewpoint sensor, 4-20 mA type in order to optimized the use of the two columns. One alarm output is present, as well as a digital input for remote ON/OFF and a serial RS485 port, implementing the ModBus protocol. A set of parameters can featuring the dryer. A 4,3 inches touch screen display with a symnotic representation of the operation status give a very user friendly interface. \r\n', 'nemaslike.jpg', 'Bayblend  plastic, self extinguishing (110 x 70 mm) ', '230Vac +/-10%, 50-60Hz |||', '', 'DISPLAY: 4,3 inches TFT display capacitive type 	       	 ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '12 parameters', 'one digital input for remote ON/OFF 		one 4-20 mA input for dewpoint', 'one triac 230Vac, 1A for left column Inlet 		one triac 230Vac, 1A for left column Purge 		one triac 230Vac, 1A for right column Inlet 		one triac 230Vac, 1A for right column Purge', 'on demand', '', 'RS485 port with ModBus protocol', '2 columns absorbtion dryers', 0, NULL, 'DED705', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED705', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(70, 'DEW001', 1, 1, 'DEW001 is a pressurization system controller for an accurate and reliable control of a domestic water. A constant pressure can be maintained as well as the control of losses or the water presence. It can drive one or two pumps (in alternance or in parallel). It accepts the most common  pressure sensors. A wide range of parameters can featuring the way of operation of the controlled pressurization unit. The housing is a slim one, that can be easily fixed to the front panel of the unit.\r\n', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, panel 44 x 188 mm, suitable for 30 x 155 mm hole panel. Blocked with two screws at the front panel.', '12Vac/Vdc +/-10%, 50-60Hz |||', '', 'DISPLAY: 140 dots red with scrolling messages or data                     4 push buttons for user operation                    acoustic buzzer for alarm', '35 parameters', 'one pressure input  up to 30 Bars              one  free voltage digital inputs for  low liquid level control  	 one  free voltage digital inputs for  high liquid level control or SDS control', '2 relay 230Vac, for max. 5A  pumps                	one relays VFC type, max. 5 A for high pressure alarm                         one relays VFC type, max. 5 A for low pressure alarm 		one relays VFC type, max. 5 A for pump1 alarm                         o', 'on demand', 'pressure sensors', 'RS485 port with ModBus protocol', 'control of small, medium and big pressurization units', 0, NULL, 'DEW001', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW001', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(71, 'DED700', 2, 4, 'DED700 is a controller for compressed air dryer, base on the air cooling. It drives a compressor, a valve for draining humidity, a fan for condensator. Using a set of parameters, user can featuring the way of operation of the dryer. ', 'nemaslike.jpg', 'ABS plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '230Vac +/-10%, 50-60Hz|||', '', 'DISPLAY: 3 blue LEDs digits, h=14 mm  		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '10 parameters', 'one sensor NTC 10K for dewpoint                  one sensor NTC 10K for condensator', 'one relay 230Vac, 10A for compressor  		one triac 230Vac, 3A for fan                	 one triac 230Vac, 1A for drain', 'on demand', 'sensor NTC10K', '', 'small and medium dryers', 0, NULL, 'DED700', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED700', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(72, 'DED701', 2, 4, 'DED701 is a controller for compressed air dryer, base on the air cooling. It drives a compressor, a valve for draining humidity, a fan for condensator and an alarm output. Using a set of parameters, user can featuring the way of operation of the dryer. \r\nA RS485 port implementing the ModBus protocol is present.', 'nemaslike.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '230Vac +/-10%, 50-60Hz|||', '', 'DISPLAY: 3 red LEDs digits, h=14mm  		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '12 parameters', 'one sensor NTC 10K for dewpoint                  one sensor NTC 10K for condensator', 'one relay 230Vac , 10A for compressor  		one triac 230Vac, 3A for fan                	one triac 230Vac, 1A for drain                         one triac 230Vac, 50mA for alarm', 'on demand', 'sensor NTC10K', 'RS485 port with ModBus', 'small and medium dryers', 0, NULL, 'DED701', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED701', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(73, 'DED702', 2, 4, 'DED702 is a controller for compressed air dryer, base on the air cooling. It drives a compressor, a valve for draining humidity, a fan for condensator and an alarm output. Using a wide set of parameters, user can featuring the way of operation of the dryer.  The fan speed control gives a very accurate control of the dewpoint.\r\nThe board is supplied without housing, so can be fixed to the panel of the dryer with a customized label.', 'nemaslike.jpg', 'free board to be fixed to the front panel of the dryer', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			115Vac +/-10%, 50-60Hz | 			24Vac +/-10%, 50-60Hz ', '', 'DISPLAY: 3 red LEDs digits, h=14mm  		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor', '30 parameters', 'one sensor NTC 10K for dewpoint                  one sensor NTC 10K for condensator', 'one relay 230Vac, 10A for compressor  		one triac  230Vac, 3A for fan                	one relay 230Vac, 8A for drain                         one relay 230Vac, 5A for alarm', 'on demand', 'sensor NTC10K', '', 'small and medium dryers', 0, NULL, 'DED702', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED702', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(74, 'DED703', 2, 5, 'DED703 is a simple controller for absorbtion small dryers, based on two triac alternatively driving valves. ', 'nemaslike.jpg', 'ABS plastic, self extinguishing, suitable for 29x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '230Vac +/-10%, 50-60Hz|||', '', 'one led shows the controller status', '', '', 'two triacs 230Vac,1A, one for each column', '', '', '', 'small absorbtion dryers', 0, NULL, 'DED703', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DED703', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(75, 'DEW002', 1, 1, 'DEW002 is a pressurization system controller for an accurate and reliable control of a domestic water. A constant pressure can be maintained as well as the control of losses or the water presence. It can drive one or two pumps (in alternance or in parallel). It accepts the most common  pressure sensors. A wide range of parameters can featuring the way of operation of the controlled pressurization unit. The housing is a slim one, that can be easily fixed to the front panel of the unit. It can work as stand alone unit or in connection with DEW810 expansion module via proprietary serial port. The controller can be used also with degassing systems in order to remove air from water pipes.', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, panel 44 x 188 mm, suitable for 30 x 155 mm hole panel. Blocked with two screws at the front panel.', '12Vac/Vdc +/-10%, 50-60Hz|||', '', 'DISPLAY: 140 dots red with scrolling messages or data                     4 push buttons for user operation                    acoustic buzzer for alarm', '58 parameters', 'one pressure input  up to 30 Bars              one free voltage digital inputs for low liquid level control  	 one free voltage digital inputs for high liquid level control or SDS control', '2 relay 230Vac, for max. 12A  pumps                	one relays VFC type, max. 5 A for high pressure alarm                         one relays VFC type, max. 5 A for low pressure alarm 		one relays VFC type, max. 5 A for pump1 alarm                         ', 'on demand', 'pressure sensors', 'RS485 port with ModBus protocol                       Software supervisor and programming tool available', 'control of small, medium and big pressurization units', 0, NULL, 'DEW002', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW002', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(76, 'DEW003', 1, 1, 'DEW003 is a pressurization system small controller for an accurate and reliable control of a domestic water. A constant pressure can be maintained as well as the control of losses or the water presence. It can drive one or two pumps (in alternance or in parallel). It accepts the most common  pressure sensors. A range of parameters can featuring the way of operation of the controlled pressurization unit. The housing is a 32 x 74 mm size (front panel), that can be easily fixed to the front panel of the unit. ', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', 'selectable between:| 			230Vac +/-10%, 50-60Hz | 			12Vac +/-10%, 50-60Hz', '', 'DISPLAY: 3 red LEDs digits, h=14mm 		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 4 push buttons for user operation                 	acoustic buzzer for alarm', '12 parameters', 'one pressure input  up to 30 Bars              one free voltage digital inputs for SPC interface 	 one free voltage digital inputs for low vacuum detection              one free voltage digital inputs for additive function 	 one free voltage digital input', '2 relay 230Vac, for max. 12A  pumps                	one relays VFC type, max. 8 A for purge                         one relays VFC type, max. 8 A for slam shut 		one relays VFC type, max. 8 A for break tank                         one relays VFC type, max', 'on demand', 'pressure sensors', '', 'control of small and medium pressurization units', 0, NULL, 'DEW003', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW003', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(86, 'DEW004', 1, 1, 'DEW004 is a pressurization system small controller for an accurate and reliable control of a domestic water. A constant pressure can be maintained as well as the control of losses or the water presence. It can drive one or two pumps (in alternance or in parallel). It accepts the most common  pressure sensors . A range of parameters can featuring the way of operation of the controlled pressurization unit. The housing is a 32 x 74 mm size (front panel), that can be easily fixed to the front panel of the unit. The controller can drive an external UV light for water bacteria disinfection. ', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '12Vdc +/-10%|||', '', 'DISPLAY:105 red dots  		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 4 push buttons for user operation                 	acoustic buzzer for alarm', '17 parameters', 'one pressure input  up to 16 Bars, 4-20mA              one free voltage digital input for liquid level or              one sensor for max. pump temperature alarm ', 'two relay 230Vac, for max. 5A pumps                	one relays VFC type for alarm                          one 12Vdc for driving an external relay for UV light', 'on demand', 'pressure sensors', '', 'control of small and medium pressurization units', 0, NULL, 'DEW004', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW004', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(78, 'DEH010', 4, 6, 'DEH010 is small board to insert into a water heating resistor up to 2KW. The temperature can be set via a potentiometer  and, through a triac, the board controls the energy to the heating resistor. A  led shows the ON/OFF status of heater.', 'nemaslike.jpg', 'no housing, board has to be inserted in the electrical heater', '230 Vac +/-10%, 50-60 Hz|||', '', 'one potentiometer fixes the wanted temperature', '', '', 'Triac 230Vac - 8A', '', '', '', 'in heating resistor for domestic application (for example: bathroom)', 0, NULL, 'DEH010', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEH010', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(80, 'DEH011', 4, 6, 'DEH011 is a low energy, microprocessor based, thermostat supplied without housing, that can be placed inside any kind of electrical heating system up to 2,5 Kw or heating radiator, in the front panel of it and covered with a polycarbonate label. It has a 4 digits blue display and two push buttons. Using the buttons operator can set the wanted temperature between 10 an 30 °C as well as put the thermostat in OFF or FROST PROTECTION status or enter in parameter programming. A proportional-integral routine controls the accurate reaching of temperature setpoint. In parallel, a second software control limits the maximum temperature of the radiator in order to prevent it to become too high. Besides, a third control stops the heater when a dangerous limit is reached, starts the  message and the acoustic alarm.  A ground connection fail detection is also present.', 'nemaslike.jpg', '', '230 Vac +/-10%, 50-60 Hz|||', '', '4 digits, 7 mm high, LED blue display 		two push buttons 		one acoustic buzzer', ' 3 parameters', 'one NTC 10 sensor for room temperature 		one NTC 10 sensor for radiator maximum temperature ', ' 2 parallel triac 230Vac - 6A for heater', 'on demand', 'NTC10K sensors', '', 'domestic heating system ', 0, NULL, 'DEH011', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEH011', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(81, 'DEH020', 4, 7, 'DEH020 is a simple and easy to use thermostat. It is realized inside a plastic housing with plugs suitable to insert directly in the main power socket. A knob on the front cover of the thermostat allows to fix the wanted temperature between 5 and 35 °C. A 3 wires (or 5 wires) cable connects thermostat to the heating system.', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing', '230 Vac +/-10%, 50-60 Hz|||', '', 'Potentiometer to fix temperature between 5 and 35 °C', '', 'one NTC 10 sensor for room temperature 		one NTC 10 sensor for heater maximum  temperature (5 wires version)', 'one relay 230Vac - 10A for heater', '3 wires (5 wires) cable with insulation shield for 20A max', '', '', 'domestic heating system controls', 0, NULL, 'DEH020', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEH020', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(82, 'GL01', 6, 15, 'GL01 is a device used to remotely manage industrial or commercial processes . Using a very powerful GSM device, it can be set to read, periodically or on request, digital or analog variables. It has 4 digital inputs, 4 analog inputs, 4 relay outputs. Thanks to the powerful parameters set, the device can monitor the digital or analog variables, comparing with the alarm set levels, switch the relay outputs and transmit the information to a service company. Depending on the used sensors the managed variables can be temperatures, pressures, humidities, liquid level switches etc.', 'gl01aa.jpg', '8 modules DIN RAIL housing', '230Vac +/-10%, 50-60Hz|||', 'Siemens TC63I', 'ANALOG INPUT ACCURACY: +/- 0,5% conversion', '', 'ANALOG INPUTS: N°4, 2-20 mA type 	DIGITAL INPUTS: N°4, free voltage contact', '4 relays, 2 A max., N.O. contact', '', '', '', 'Remote controls of temperature or pressures or voltages or humidity etc.', 0, NULL, 'GL01', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'GL01', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(83, 'GL02', 6, 15, 'GL02 is a device used to remotely manage industrial or commercial processes. Using a very powerful GSM device, it can be set to read, periodically or on request, digital or analog variables. It has 4 digital inputs, 4 analog inputs, 4 relay outputs. Thanks to the powerful parameters set, the device can monitor the digital or analog variables, comparing with the alarm set levels, switch the relay outputs and transmit the information to a service company. Depending on the used sensors the managed variables can be temperatures, pressures, humidities, liquid level switches etc. ', 'gl02aa.jpg', '8 modules DIN RAIL housing', '230Vac +/-10%, 50-60Hz|||', 'Siemens TC63I', 'ANALOG INPUT ACCURACY: +/- 0,5% conversion', '', 'ANALOG INPUTS : N°2, 2-20mA type 		DIGITAL INPUTS: N°2, free voltage contact', '2 relays, 2 A max., N.O. contact', '', '', '', 'Remote controls of temperature or pressures or voltages or humidity etc.', 0, NULL, 'GL02', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'GL02', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(90, 'DEW820', 1, 2, 'DEW820 is a filter monitor for improving the control of a domestic water system. Using two pressure sensor at inlet and outlet of the water filter, it gives alarm when the pressure drop is higher of the prefixed one, so meaning that the filter has be be changed. Besides, it monitors the status of the pump and when it fails one alarm is generated. It can drive one pump and accepts the most common pressure sensors. A range of parameters can featuring the way of operation of the filter monitor. The housing is a 32 x 74 mm size (front panel), that can be easily fixed to the front panel of the unit. ', 'nemaslike.jpg', 'Bayblend plastic, self extinguishing, suitable for 29 x 68 mm hole (32 x 74 mm panel). Blocked with a plastic clamp.', '12Vdc +/-10%|||', '', 'DISPLAY:105 red dots  		ACCURACY: +/- 0,5°C (A/D conversion), +/- 1 °C sensor 4 push buttons for user operation                 	acoustic buzzer for alarm', '9 parameters', 'two pressure input up to 16 Bars, 4-20 mA', 'one relay 230Vac, for max. 5A pump                	one relays VFC type for pump/filter alarm  		one relays VFC type for common alarm', 'on demand', 'pressure sensors', '', 'monitoring of water filter / pump in domestic application', 0, NULL, 'DEW820', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEW820', '', '', '', '', '', '', '', '', '', '', '', '', NULL),
(92, 'DEH001', 4, 10, 'DEH001 is a very powerful and simple temperature controller for domestic application. It consists of two parts: the user interface display that can be placed on the wall and the power unit that must be placed in the heating system. It controls the room temperature, the water maximum pressure, the status of the pump, the maximum temperature of water and the maximum supplied energy. Equipped with a GSM industrial mobile, it can be programmed remotely and can send via sms all the main informations about the heating system status. \r\nBesides, two daily programs can be settled and applied to the days of the week. ', 'nemaslike.jpg', 'Bayblend plastic housing V0 fire protection and free board', '380Vac +/-10%, 50-60Hz, |3-phases||', 'Telit GM865 ', 'blue back lighted 50 icons LCDisplay 		four capacitive switches   		one acoustic buzzer 		RTC for temperature time program', '31 parameters', 'one on board NTC 10 sensor for room temperature       		one external NTC 10 sensor for accurate room temperature 		one NTC 10 sensor for water maximum temperature                          one digital input for maximum pressure pressostat', 'one triac 380 Vac - 6 A for water pump 		two triacs 380 Vac - 6 A heater on phase 1 		two triacs 380 Vac - 6 A heater on phase 2 		two triacs 380 Vac - 6 A heater on phase 3', 'on demand', 'NTC10K sensors', 'GSM comunication and application', 'complete heating systems based on boiler, water pipes and electrical heating of water', 0, NULL, 'DEH001', '', '', '', '', '', '', '', '', '', '', '', '', NULL, 'DEH001', '', '', '', '', '', '', '', '', '', '', '', '', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`),
  ADD KEY `subcategory_id` (`subcategory_id`) USING BTREE;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=93;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
