-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 03, 2020 at 09:43 AM
-- Server version: 5.7.23
-- PHP Version: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `products_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Lemilice i propratna oprema'),
(2, 'Manualni sistemi'),
(3, 'Izvlačenje isparenja'),
(4, 'Automatski sistemi'),
(5, 'Oprema za vizuelnu kontolu'),
(6, 'Roboti'),
(7, 'Antistatički program');

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

DROP TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `categories_id` int(11) NOT NULL,
  `subcategory` varchar(255) COLLATE utf8_bin NOT NULL,
  `title` varchar(150) COLLATE utf8_bin NOT NULL,
  `rb` int(11) NOT NULL,
  `slug` varchar(250) COLLATE utf8_bin NOT NULL,
  `proizvodjac` varchar(50) COLLATE utf8_bin NOT NULL,
  `product_image` varchar(255) COLLATE utf8_bin NOT NULL,
  `karakteristike` varchar(255) COLLATE utf8_bin NOT NULL,
  `opis` text COLLATE utf8_bin NOT NULL,
  `preporucujemo` tinyint(1) NOT NULL,
  `url` varchar(255) COLLATE utf8_bin NOT NULL,
  `sizes` varchar(255) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  KEY `product_ibfk_1` (`categories_id`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `categories_id`, `subcategory`, `title`, `rb`, `slug`, `proizvodjac`, `product_image`, `karakteristike`, `opis`, `preporucujemo`, `url`, `sizes`) VALUES
(20, 1, 'Lemilice', 'Lemilica TMT-9000S', 0, 'Lemilica-TMT-9000S', 'Thermaltronics', 'tmt-9000s.jpg', 'Curie Heat Technologija koji radi na 13.56MHz, Visok termički oporavak i performanse, Dva izlaza za rad i LCD ekranom, Koristi T seriju vrhova, Nije potrebna kalibracija ili obuka operatera, Snaga: 40W', 'Lemilica TMT-9000S zasnovana je na tehnologiji Curie Heat koja reaguje na toplotne potrebe svakog lemnog spoja. Samopodešavanjem snage (toplote) ispunjava tačni zahtev komponente i materijala za lemljenje na PCB ploči. Brzina dostizanje snage (temperature) za rad je oko 4 sekunde. Na samoj stanici moguće je priključiti razlemljivač (pištolj) i termo pincetu. Postoji mogućnost naizmeničnog rada na stanici za dve različite aplikacije. Veoma pogodan za složene zahtevne samih aplikacija. - Opširnije informacije za razlemljivač (pištolj) i termo pincete možete videti u podkategoriji \"Propratna oprema i materijal\". - Izbor vrhova iz Serije M mozete videti na \"Detaljnije na sajtu proizvođača\"', 1, 'http://www.thermaltronics.com/tmt-9000s.php', ''),
(21, 1, 'Lemilice', 'Lemilica TMT-5000S', 1, 'Lemilica-TMT-5000S', 'Thermaltronics', 'tmt-5000s.jpg', 'Curie Heat Technologi koji radi na 13,56MHz, Jedan izlaz za rad, Koristi T seriju vrhova, Lagan i kompaktan, Nije potrebna kalibracija ili obuka operatera, Snaga: 30W', 'Lemilica TMT-5000S zasnovana je na tehnologiji Curie Heat koja reaguje na toplotne potrebe svakog lemnog spoja. Samopodešavanjem snage (toplote) ispunjava tačni zahtev komponente i materijala za lemljenje na PCB ploči. Brzina dostizanje snage (temperature) za rad je oko 5 sekundi. Na samoj stanici moguće je priključiti razlemljivač (pištolj) i termo pincetu. - Opširnije informacije za razlemljivač (pištolj) i termo pincete možete videti u podkategoriji \"Dodatna oprema i materijal\". - Izbor vrhova iz Serije T mozete videti na \"Detaljnije na sajtu proizvođača\"', 0, 'http://www.thermaltronics.com/tmt-5000s.php', ''),
(22, 1, 'Propratni-materijal', 'Automatski dodavač kalaja AF-KIT', 0, 'Automatski-dodavac-kalaja-AF-KIT', 'Thermaltronics', 'af-kit-1.jpg', 'Podesiva brzina i dužina dodavanja kalajne žice,  Podesivo uvlačenje kalajne žice, Uredjaj omogućava preciznu kontrolu, Povećava efikasnost', 'Automatski dodavač kalaja AF-KIT omogućava rad u jednoj ruci za vreme lemljenja. Komplet se isporučuje kao dodatak postojećim Thermaltronics sistemima za ručno lemljenje.', 0, 'http://www.thermaltronics.com/af-kit.php', ''),
(23, 6, 'Propratni-materijal', 'Automatski čistač vrha TMT-ASTC', 0, 'Automatski-cistac-vrha-TMT-ASTC', 'Thermaltronics', 'tmt-astc100.jpg', 'Uklanja sa vrha kalaj i oksidacije, Lagan i kompaktan, Lako se čisti i održava', 'Automatski čistač vrha TMT-ASTC ukljanja ostatke kalaja i oksidacije sa vrha. Sistem se sastoji iz dve visoko kvalitetne mesingane četke, koje se okreću u suprotnim smerovima.', 0, 'thermaltronics.com/tmt-astc100.php', ''),
(24, 1, 'Propratni-materijal', 'Dodavač kalajne žice TMT-SSH100', 0, 'Dodavac-kalajne-zice-TMT-SSH100', 'Thermaltronics', 'tmt-ssh100.jpg', 'Precizno dodavanje kalajne žice, Kontinuirano pušta žicu za lemljenje, Operater ne mora da ručno radi sa žicom, Precizno i udobno lemljenje', 'Držač kalajne žice TMT-SSH100 koristi visokokvalitetni sistem koji pomaže da se glatko i brzo doziraju žice za lemljenje.', 0, 'http://www.thermaltronics.com/tmt-ssh100.php', ''),
(25, 4, 'p-and-p', 'Desktop Pick&place KAYO-D2V-25S', 0, 'Desktop-Pickplace-KAYO-D2V-25S', 'KAYO', 'KAYO-D2V-25S.jpg', 'Drawer type computer and driver integrated, Disassembled chassis, easy to handling, HD industrial camera, precisely identify 0402, Intelligent remounting design, Component auxiliary box design, Software is easy to understand and use', 'KAYO-D2V-25S is the classic of desktop dual-head SMT pick and placement machine. High precision, more reasonable mechanical design, easy operation, stable running, adapting air-operated feeder, automatic vision system, automatic detection materials shortage. Suitable for mounting most of the SMD components, such as 0402 0603 0805 1206 1210 3528 5050 SOP QFN, etc.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/342/id/289.html', ''),
(26, 4, 'p-and-p', 'Pick&Place KAYO-A4', 0, 'PickPlace-KAYO-A4', 'KAYO', 'KAYO-A4.jpg', 'High Precision, The max. mounting speed: 7000CPH, Average mounting speed: 5000CPH,  Full Automation: With rail guide,  Strong Stability: Panasonic Servo Motor and Drive, Could effectively mount 0402-5050 components', 'High Precision: Equipped with 6pcs of cameras: 1pc of Mark recognition camera, 1pc of 500 million pixels high precision recognition camera, and 4pcs of synchronous high-speed recognition cameras, could effectively mount 0402-5050 components, LED beads, diodes, transistors, SOP, 40mm*40mm range pin pitch ≥0.3mm chip QFP, BGA etc.  Strong Stability: Panasonic Servo Motor and Drive, TBI high-precision grinding ball screw rod + heavy-duty linear guide, Japan Vacuum generator, JUKI high-precise nozzles, automatic feeding integrated system and high-configuration IPC - High precision, strong stability, promise 24-hour mounting stably.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/342/id/321.html', ''),
(27, 4, 'p-and-p', 'Pick&Place KAYO-A4L', 0, 'PickPlace-KAYO-A4L', 'KAYO', 'KAYOA4L.jpg', 'High Precision: Equipped with 6pcs of cameras, Fast Speed: the max. mounting speed: 8000CPH, average mounting speed: 6000CPH, Strong Stability: Panasonic Servo Motor and Drive', 'Optimized multi-functional conveyor (best positioning + no impact stopping), adopt a laser sensor rather than mechanical stopper to position. No rely on the PCB board size, shape, achieve the best positioning and no impact stop.\r\nHigh Precision: Equipped with 6pcs of cameras: 1pc of Mark, 1pc of high precision, and 4pcs of high-speed recognition cameras, could effectively mount 0402-5050 components, beads, diodes, transistors, SOP, 45mm*45mm range pin pitch ≥0.3mm chip QFP-256, BGA etc.\r\nTBI precise linear guide and ball screw, Japan Vacuum generator, JUKI high-precise nozzles, automatic feeding integrated system and high-configuration IPC - High precision, strong stability, promise 24-hour mounting stably.', 1, 'http://en.kayosmt.com/index.php/Show/index/cid/342/id/290.html', ''),
(28, 4, 'p-and-p', 'Pick&Place KAYO-1706-3DSG', 0, 'PickPlace-KAYO-1706-3DSG', 'KAYO', 'KAYO-1706-3DSG.jpg', '6 heads, 8pcs of cameras, Quick positioning, Low noise, High precision, Imported heavy-duty linear guide', 'Three-section transmitting boards-automatic connection from left to right (The first section is waiting for mounting, the second section is responsible for mounting (When the PCB board finishes mounting and transmits to the third section, the first section also receives the demand to prepare a new boards simultaneously.), the third section transmits the board from p&p machine to reflow oven. Effectively save time of transmitting boards and improve efficiency.\r\nPanasonic Servo Motor and Drive, TBI precise linear guide, Japan Vacuum generator, JUKI high-precise nozzles, automatic feeding integrated system and high-configuration IPC - High precision, strong stability, promise 24-hour mounting stably.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/342/id/291.html', ''),
(29, 4, 'p-and-p', 'Pick&Place KAYO-A8L', 0, 'PickPlace-KAYO-A8L', 'KAYO', 'KAYO-A8L.jpg', '8 heads, Total 10pcs of cameras, Adopt imported JUKI nozzle spring buffer, Precision control error can reach 0.018mm, Adopt Japan Panasonic A6 series AC servo motor, With two 17” displays', ' Change the traditional way of positive pressure turning into negative pressure to pick up components, built-in high-efficiency & energy-saving vacuum pump and vacuum tank, equipped with the latest r&d vacuum damage system. Greatly improve the efficiency of picking up the components, eliminate the noise caused by positive pressure turning into negative pressure, delay and reduce the frequency of air compressor start-up, effectively improve the life of air compressor. Can hold 70pcs of 8mm pneumatic feeders simultaneously, reserved 38 electric feeder interface, could switch feeder type at random, also could be electric, pneumatic feeder mixture. Accurately mount 0201-5050 resistance, LED lamp beads, diodes, transistor, SOP, chip QFP-256, 45mm*45mm range QFP, BGA etc.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/342/id/292.html', ''),
(30, 2, 'Manualni-printeri', 'Manualni štampač za SMD - KAYO-P1000', 0, 'Manualni-stampac-za-SMD-KAYO-P1000', 'KAYO', 'stampac3.jpg', 'Nanošenje paste za lemljenje na jednostranoj i dvostranoj PCB ploči, Max veličina PCB: 250 x 400mm, Max veličina šablona: 300 x 400mm, Max visina dvostrane ploče: 80 mm, Podešavanje šablona: vertikalno/horizontalno  +/-10mm, Visina platforme: 190mm', 'Manualni štampač za nanošenje paste za lemljenje na PCB ploče. Nanošenje paste ili lepka za lemljenje na jednostranoj i dvostranoj PCB ploči. Uredjaj je izrađen od nerđajućeg čelika. Pozicioniranje PCB ploča vrši se na pričvrsnim pinovima. Brzo podešavanje šablona po X,Y osi i visini pomoću prikladnih ručki. Pouzdano pričvršćivanje šablona sa 4 vijka. Poravnavanje PCB-a i šablona.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/283.html', ''),
(31, 4, 'Stencile-printeri', 'Polu-automatski štampač KAYO-5088', 0, 'Polu-automatski-stampac-KAYO-5088', 'KAYO', '1KAYO-5088.jpg', 'Microcomputer control, Touch screen display, Menu operating interface,  Using two-hand button switch operation, Safe and reliable, Scraper pressure adjustable', ' Touch screen menu can independently set the whole steel net pause time up and down PCB positioning methods include reference hole positioning, reference edge positioning, reference hole & edge positioning at the same time, template positioning, etc Touch screen with time display function, printing times count function automatically, screen protection function. With scraper speed adjusment function and emergency stop safety function Printing Mode: single, double, second start (menu settings optional). Printing working status: automatic / semi-automatic / jogging three printing status (menu settings optional). Cast iron table, work smoothly, no jitter phenomenon.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/280.html', ''),
(32, 4, 'Stencile-printeri', 'Polu-automatski štampač KAYO-5088C', 0, 'Polu-automatski-stampac-KAYO-5088C', 'KAYO', '1KAYO5088C.jpg', 'Microcomputer control, Touch screen display, Menu operating interface, Scraper speed adjustment function, Emergency stop safety function', 'Scraper pressure adjustable (according to the length of the different types of scraper blade, adjust the pressure to the steel). Equipped with the inverter speed control system, scraper running speed is steady. Using two-hand button switch operation, safe and reliable. Touch screen menu can independently set the whole steel net pause time up and down. PCB positioning methods include reference hole positioning, reference edge positioning, reference hole & edge positioning at the same time.Printing Mode: single, double, second start (menu settings optional)Printing working status: automatic / semi-automatic / jogging three printing status (menu settings optional). Cast iron table, work smoothly, no jitter phenomenon.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/320.html', ''),
(33, 4, 'Stencile-printeri', 'Polu-automatski štampač KAYO-5088L', 0, 'Polu-automatski-stampac-KAYO-5088L', 'KAYO', '5088L.jpg', 'Scraper pressure adjustable, Safe and reliable,  Microcomputer control, Touch screen display, Menu operating interface, Equipped with the inverter speed control system', 'Touch screen menu can independently set the whole steel net pause time up and down. PCB positioning methods include reference hole positioning, reference edge positioning, reference hole & edge positioning at the same time, template positioning, etc. Touch screen with time display function, printing times count function automatically, screen protection function. With scraper speed adjustment function and emergency stop safety function. Printing Mode: single, double, second start (menu settings optional). Printing working status: automatic / semi-automatic / jogging three printing status (menu settings optional). Cast iron table, work smoothly, no jitter phenomenon.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/284.html', ''),
(34, 4, 'Stencile-printeri', 'Automatski štampač KAYO-400', 0, 'Automatski-stampac-KAYO-400', 'KAYO', '1KAYO400.jpg', 'Compatible with a wide range of PCB, High precision printing resolution, Automatic stencil frame positioning, Automatic PCB correction, Automatic scraper pressure adjustment, Automatic stencil frame cleaning', 'Adopt independently developed floating printing head, the automatic adjustment system of the programmable scraper pressure, automatically balance the scraper pressure, with precise pressure control, can achieve the perfect solder paste forming effect. Programmable motor controls scraper and stencil frame separation speed and stroke, can flexibly achieve a variety of demoulding methods. Multi-functional PCB fixed positioning system, PCB positioning convenient, fast and accurate. Up and down visual positioning system. Built-in image processing system. Support 2D, SPC function. The printing translation is driven by the motor directly connected to the timing belt.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/285.html', ''),
(35, 4, 'Stencile-printeri', 'Automatski štampač KAYO-450', 0, 'Automatski-stampac-KAYO-450', 'KAYO', '1KAYO450.jpg', 'Precision, Special adjustment platform, Using windows XP operating system, Programmable suspension self-adjusting stepper motor, PCB positioning system, Automatic cleaning structure, High adaptability steel mesh frame clamping system, Electronic control s', 'Independent direct-connected stepper motor control, built-in precision pressure control system, can accurately measure the blade original pressure value, without consider blade type, length, weight or thickness changes. Programmable realizes printing process flexible; Designed according to front and rear blade required different pressure & the stability of the lift to prevent solder paste leakage and the blade with a certain flexibility of the clamping design, blade pressure, lifting speed, printing speed, printing range are adjusted through software, and provide customers a variety of stripping module ways to adapt PCB with different tin requirements, providing a good printing control platform for customers. Realize the printing of various meshes’ sizes (370mm x 470mm ~ 737mm x 737mm), and can realize the rapid replacement model in the production process; Y direction automatic positioning. Adopt self-developed modular integrated circuits, safe, easy maintenance; use the most advanced industrial control system, achieve to modify the parameters during operation.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/282.html', ''),
(36, 4, 'Stencile-printeri', 'Automatski štampač KAYO-600', 0, 'Automatski-stampac-KAYO-600', 'KAYO', '1KAYO600.jpg', 'Simple and reliable structure, Adaptive PCB thickness, PCB positioning system, New light path system, Dry cleaning, Wet washing, Vacuum three cleaning methods, High adaptability steel mesh frame clamping system,  English user interface', 'Dedicated math model with Repeatability±15μm (± 0.0005 \") @ 6 σ, Cp≥2.0. Ensure the machine to achieve high precision alignment.  Intelligent and fast matching of different thickness PCB boards with their transmission and clamping mechanisms. Designed for the different front and rear blade pressure requirements and the stability of the lift, to prevent the solder paste from leaking and the blade has a certain elastic clamping design, the blade pressure, lifting speed, printing speed, printing range are all adjusted by software, provide customers with a variety of demoulding methods to adapt to different tin-plated PCB boards. Rail-type intelligent scraper system for improving operational stability and extending service life.', 1, 'http://en.kayosmt.com/index.php/Show/index/cid/345/id/281.html', ''),
(37, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF330', 0, 'Reflow-pec-KAYO-RF330', 'KAYO', 'KAYO-RF330.jpg', '3 Heating Zones, Stainless steel conveyor belt, Power saving, Exhaust port, Alarm protection function, ', 'Adopt the latest streamlined design, the appearance of the whole machine is integration, the upper, middle and lower can be arbitrarily disassembled and assembled to facilitate customers upstairs and downstairs, all configuration interface using plug-in type, to facilitate future maintenance. Built-in rotating flywheel, free to transfer. Without trouble by power outages, making the temperature of the heating zone fully radiating, the thermal expansion coefficient of the stainless steel mesh belt are same, effectively extend the service life of the equipment.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/317.html', ''),
(38, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF430', 0, 'Reflow-pec-KAYO-RF430', 'KAYO', 'KAYO-RF430.jpg', '4 Heating Zones, 8pcs of controlling meters, Italian high-temperature high-speed motor, The intelligent micro-computer precision controller, Reliable and smooth transmission system, Stable and reliable electrical control system', 'High efficiency and energy-save Swedish 110V nickel chromium heating pipe is used in heating system (replacement within three year), radiation power peak wavelength 4UM, equipped with surface reflector, high thermal efficiency, rapid heating speed, specially-made strong hot air cycle structure system, making PCB and components heating equally, completely eliminate the shadow effect. Adopt imported high-current solid-state relay non-contact output, safe and reliable, combined with the temperature controller which has unique fuzzy control function, always monitoring the outside temperature and heat value changes, control heating components with minimize pulse , fast response to ensure temperature control accuracy ±1℃, the error of inside temperature distribution ±2℃. Temperature distribution in the length direction conform to IPC standards.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/316.html', ''),
(39, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF530', 0, 'Reflow-pec-KAYO-RF530', 'KAYO', 'KAYO-RF530.jpg', '5 Heating Zones, PID overall temperature control, Easy to operate, Ultra high temperature resistant motor, Precisely layout distribution box, High quality fan', 'Thickening aluminum plate could be more evenly distributed heat, better heat dissipation, more durable. The distribution box is precisely layout in the rear side of the machine for easy maintenance. It is extremely safe in both materials and design. Equipped with air switch, fuse, over temperature protection. Oven adopt 800 degree High temperature resistant & corrosion resistant finish. Adopt ultra high temperature resistant motor, fast heat dissipation, high safety, greatly reducing the failure caused by excessive temperature. External heating zones instrument and transport adjustment, which is more convenient for the customers to detect the temperature change and speed adjusting status, make sure the quality of the soldering. Newest PID micro-computer overall temperature control system, which provides precise temperature control, quick heating-up, low energy consumption and high efficiency.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/318.html', ''),
(40, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF630', 0, 'Reflow-pec-KAYO-RF630', 'KAYO', 'KAYO-RF630.jpg', '6 Heating Zones, Reliable and smooth transmission system, Advanced and long-life heating system, 12pcs of controlling meters,  Special stainless steel type mesh belt', 'High efficiency and energy-save Swedish nickel chromium heating pipe is used in heating system, radiation power peak wavelength 4UM, equipped with surface reflector, high thermal efficiency, rapid heating speed, specially-made strong hot air cycle structure system, making PCB and components heating equally, completely eliminate the shadow effect. Transmission system adopts Japan Matsushita stepless speed motor, adjustable belt speed stepless speed governor, smoothly operating matched up with 1:150 turbine reducer, speed 0-2000mm /min stepless adjustable, and also accurate digital Line speed indication.  Adopt independent roller structure and support, combined with supporting stainless steel mesh belt, running smoothly, precise speed up to ±20mm/min', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/315.html', ''),
(41, 4, 'Peći-lemljenje', 'Reflow peć KAYO-610L', 0, 'Reflow-pec-KAYO-610L', 'KAYO', 'KAYO-610L.jpg', '6 Heating Zones, Forced impact convection, Completely meet the lead-free process, High temperature control accuracy and low power consumption, Suitable for CSB and BGA component welding', '6 Heating Zones, Forced impact convection, Completely meet the lead-free process, High temperature control accuracy and low power consumption, Suitable for CSB and BGA component welding. 6 Heating Zones, Forced impact convection, Completely meet the lead-free process, High temperature control accuracy and low power consumption, Suitable for CSB and BGA component welding.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/263.html', ''),
(42, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF835', 0, 'Reflow-pec-KAYO-RF835', 'KAYO', 'KAYO-RF835.jpg', '8 Heating Zones, Patented Innovative Insulation System, Adopt precise industrial meter control,  Multi-point air injection principle, Strong forced cooling system, Multi-point air injection principle', 'Heating adopts imported special long-life wound-rotor nickel chromium heating wire, high thermal efficiency and sensitivity, small thermal inertia, the temperature controlling accuracy in each temperature zone is ±1℃; directly heating cycle air, heating up quickly, from room temperature to setting temperature about 15 minutes. Imported Taiwan Sanyue radiating type high temperature motor, directly driving hot air heating, hot air balanced, small vibration, small noise. Special transmission rail guide, made of high temperature and wear resistance stainless steel, high rigidity, lasting non-deformation. All the electrical components are imported, all the signal lines are shielded, to make the entire controlling system more stable and reliable.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/314.html', ''),
(43, 4, 'Peći-lemljenje', 'Reflow peć KAYO-800L', 0, 'Reflow-pec-KAYO-800L', 'KAYO', 'KAYO-800L.jpg', '8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side', '8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side. 8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side. 8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/261.html', ''),
(44, 4, 'Peći-lemljenje', 'Reflow peć KAYO-820L', 0, 'Reflow-pec-KAYO-820L', 'KAYO', 'KAYO-820L.jpg', '8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side', '8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side. 8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side. 8 Heating Zones, Forced impact convection, Can deal with lead-free process, High temperature control accuracy and low power consumption, Circulation of convection from side to side.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/260.html', ''),
(45, 4, 'Peći-lemljenje', 'Reflow peć KAYO-RF8845', 0, 'Reflow-pec-KAYO-RF8845', 'KAYO', 'KAYO-RF8845.jpg', 'Patented Innovative Insulation System, 8 Heating Zones, Adopt precise PLC + industrial PC control, Multi-point air injection principle, Strong forced cooling system, ', 'Adopt imported dual-layer insulation materials, to ensure the shell’s temperature of reflow oven is not higher than the indoor temperature in normal usage, greatly improving the reflow oven’s heating utilization ratio, power saving 40% than the same type of reflow oven, extremely reducing the electricity cost of reflow oven. Heating adopts imported special long-life wound-rotor nickel chromium heating wire, high thermal efficiency and sensitivity, small thermal inertia, the temperature controlling accuracy in each temperature zone is ±1℃; directly heating cycle air, heating up quickly, from room temperature to setting temperature about 15 minutes. All the electrical components are imported, all the signal lines are shielded, to make the entire controlling system more stable and reliable.\r\n\r\n', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/336/id/259.html', ''),
(46, 4, 'Talasno-lemljenje', 'Talasna mašina KAYO-250DS', 0, 'Talasna-masina-KAYO-250DS', 'KAYO', '250DS1.jpg', 'Adopts high precision, Stepless adjustable, Easy to control, Hydraulic overall clamshell structure, Fully automatic detection of PCB scanning spray', ' Adopts long-life electric heating tube with casing embedded structure, easy maintenance and replacement. Use new insulation materials.. Claw made of titanium alloy. Durable, not deformed, good consistency, keep the PCB smooth welding. Brand stir-flow motor with inverter to achieve smooth stepless speed regulation to ensure the wave soldering’s stationary. Efficient far infrared preheater, high thermal efficiency. Nozzle, motor, inverter, temperature controller, sensors, solenoid valves, optoelectronic eyes, relays are brand-name products.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/346/id/309.html', ''),
(47, 4, 'Talasno-lemljenje', 'Talasna mašina KAYO-300DS', 0, 'Talasna-masina-KAYO-300DS', 'KAYO', '300DS1.jpg', ' Body linear design, The whole processing observation window, Equipped with cooling module,  Transmission accuracy, Long life, Easy maintenance.', 'Short circuit and overcurrent protection system. Transport system closed-loop control. Stepless speed regulation, precisely control PCB preheating and welding time. Industrial computer control system dual-wave soldering device, in addition to be compatible consistent machine’s automation performance, it also adopts streamlined body design, simple and convenient computer window system, make the automated production and management records to a higher level.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/346/id/310.html', ''),
(48, 4, 'Talasno-lemljenje', 'Talasna mašina KAYO-350S', 0, 'Talasna-masina-KAYO-350S', 'KAYO', 'KAYO-350S1.jpg', 'Three independent 1.6m preheating area, Full hot air preheating, The whole processing observation window, Easy to operate and maintain, Isolated spray device', 'Transport system uses clutch limited power + current limiter dual protection. Short circuit and overcurrent protection system. Transport system closed-loop control. Stepless speed regulation, precisely control PCB preheating and welding time. Industrial computer control system dual-wave soldering device, in addition to be compatible consistent machine’s automation performance, it also adopts streamlined body design, simple and convenient computer window system, make the automated production and management records to a higher level.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/346/id/311.html', ''),
(49, 4, 'Talasno-lemljenje', 'Talasna mašina KAYO-450S', 0, 'Talasna-masina-KAYO-450S', 'Kayo', 'KAYO-450S1.jpg', 'Three independent 1.8m preheating area, full hot air preheating, Patented die-casting type titanium alloy chain claws, The whole processing observation window, With backrest design to prevent misuse damage to the machine, System fault self-diagnosis, Redu', 'Transport system uses clutch limited power + current limiter dual protection. Short circuit and overcurrent protection system. Transport system closed-loop control. Stepless speed regulation, precisely control PCB preheating and welding time. Industrial computer control system dual-wave soldering device, in addition to be compatible consistent machine’s automation performance, it also adopts streamlined body design, simple and convenient computer window system, make the automated production and management records to a higher level.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/346/id/312.html', ''),
(50, 4, 'Optička-inspekcija', 'Offline AOI KAYO-625', 0, 'Offline-AOI-KAYO-625', 'Kayo', 'KAYO-625.jpg', 'Special for small and medium-sized enterprises, Simple programming and debug mode, Automatically identify PCB, Multiple machine monitoring system, Professional SPC analysis system', ' Simple test results report: The test report contains some contents of spc, according to the real test case shows the ratio of NG and distribution, real-times show the quantity of the sting boards, parts per million, false-operator rate and other relevant information, so the operator is easy to know the detail of the production line. l Professional spc system: Professional spc analysis report to macroscopic readjustment and control the production line, reduce the incidence and raise productivity.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/338/id/300.html', ''),
(51, 4, 'Optička-inspekcija', 'Online AOI KAYO-810', 0, 'Online-AOI-KAYO-810', 'Kayo', 'KAYO-810.jpg', ' Easy to operate and muIti-functional, Simple software interface accord with daily and effective operation, The software is comprehensive and nimble, Fully meet the requirements of Iead-free process, With larger inspection size', 'The machine can work OK/NG loader, make the seamless connection of on-line testing, PCB receiving and repairing. l With the application of off-line programming and off-line debugging,making,the equipment with maximize utilization. l Various algorithm application and combination, make the application of software is more flexible. l The new algorithm OCR and short test, meet the request of quality inspection after printing more effectively. l With high intellectualized control system,it can control the quality and give feedback in the first time.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/338/id/301.html', ''),
(52, 4, 'Optička-inspekcija', 'Online AOI KAYO-800', 0, 'Online-AOI-KAYO-800', 'KAYO', 'KAYO-800.jpg', 'Easy to operate and muIti-functional AOI, Simple Interface, The software is comprehensive and nimble, l The lowest training request, With larger inspection size, Portable tracking doors design easier for maintenance', 'With the application of off-line programming and off-line debugging,making,the equipment with maximize utilization. l Various algorithm application and combination, make the application of software is more flexible. l The new algorithm OCR and short test, meet the request of quality inspection after printing more effectively. l With high intellectualized control system,it can control the quality and give feedback in the first time. l Fully meet the requirements of Iead-free process', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/338/id/319.html', ''),
(53, 4, 'Automatski-dodaci', 'PCB izlazno postolje za hladjenje KAYO-300', 0, 'PCB-izlazno-postolje-za-hladjenje-KAYO-300', 'KAYO', '1KAYO300.jpg', 'Stepless Speed Regulation, Thickened aluminum, Firm structure, Axial Flow Fan', 'Outline Size: 1200*380*1000mm. Belt Width: 300mm.. Transfer Speed: 600~2200mm/min. Cooling Fan Power: AC220V 50Hz, 60W. Control Method: Speed Adjusting Motor. PCB Transmission Direction: Left→Right. Cooling Fan: 2pcs. Total Power: AC220V 100W. Track Material: Aluminum Alloy. Net Weight: 50KGS.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/359/id/327.html', ''),
(54, 4, 'Automatski-dodaci', 'Unloader KAYO-50S', 0, 'Unloader-KAYO-50S', 'Kayo', 'Unloader-KAYO-50S.jpg', 'Special aluminum alloy body, better to know the working status of magazines, Solid cast lift design improving the stability, Panasonic PLC Control. Multi-functional electrical circuits and program design, PCB transmission speed adjustable', 'User-friendly programming, 4 PITCH chooses, can set the step of receiving/sending PCB. Standard SMEMA interface can be connected with other automation equipment. Using engineering plastic flat strip for magazine’s transmission. Three-point positioning, up-down pneumatic clamping to ensure accurate location of magazines. Pushing protection system ensures the PCB will not be damaged.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/359/id/325.html', ''),
(55, 4, 'Automatski-dodaci', 'Inspekcijski Conveyor-i ', 0, 'Inspekcijski-Conveyor-i', 'KAYO', 'inspeckonvejer.jpg', 'Two screws adjust rails\' width convenient and accurate, Standard ESD platen and lighting device (Optional), Power Source: Single-phase 220V 50/60HZ 100W, Transmission Speed: 0.5-400mm/min.', 'Used to connect SMT and AL production line, as well as PCB  buffering, inspection, testing and inserting. Two screws adjust rails\' width, convenient and accurate. Convey stably, stuck board will not happen. Adjustable Speed control. Standard ESD platen and lighting device (Optional). According to clients\' requirements to customize rails\' length and board placement quantity.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/359/id/323.html', ''),
(56, 4, 'Automatski-dodaci', 'Loader KAYO-50P', 0, 'Loader-KAYO-50P', 'Kayo', 'Loader-KAYO-50P.jpg', 'Touch screen controlling panel,  Special aluminum alloy body, User-friendly programming, PCB transmission speed adjustable, Pushing protection system ensures the PCB will not be damaged', ' Three-point positioning, up-down pneumatic clamping to ensure accurate location of magazines. Standard SMEMA interface can be connected with other automation equipment. User-friendly programming, 4 PITCH chooses, can set the step of receiving/sending PCB. Using engineering plastic flat strip for magazine’s transmission.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/359/id/324.html', ''),
(57, 4, 'Automatski-dodaci', 'Mixer kalajne paste KAYO-500S', 0, 'Mixer-kalajne-paste-KAYO-500S', 'KAYO', '500S1.jpg', 'Running Speed: 800, l Motor Rotational Speed: 1350 RPM, l One revolution: 400RPM, l Two rotations: 300RPM, l Operational Capability: 0-1000g * 2 tanks', 'Acceptance of Paste Solder Cream Pot: Tank diameter Φ60-Φ70 standard configuration (suitable for general 500g solder cream bottle). Time Setting: 0.01s～99H99s, minute and second set. Display Mode: LED digital display. Rated Power: Constant speed 60W. Power Supply: AC 220V 50Hz, Dimensions: 400×400×520mm. Weight: 45KG.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/359/id/326.html', ''),
(58, 4, 'Automatski-dodaci', 'YAMAHA Pneumatski Fideri', 0, 'YAMAHA-Pneumatski-Fideri', 'KAYO', 'Feeder.jpg', 'Material: High-grade Aluminum Alloy, Material: High-grade Aluminum Alloy, Suitable for belt width is 24mm, two-terminal and 24mm wide tape packaged components, Suitable for filling materials', 'Material: High-grade Aluminum Alloy, Material: High-grade Aluminum Alloy, Suitable for belt width is 24mm, two-terminal and 24mm wide tape packaged components, Suitable for filling materials.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/348/id/305.html', ''),
(59, 4, 'Automatski-dodaci', 'Vakum Nozzle', 0, 'Vakum-Nozzle', 'KAYO', 'Nozzle.jpg', '501; komponente: 0402-0603, 502; komponente: 0603-0805, 503; komponente:0805-1206, 504; komponente: 3508-5050, 505; komponente: 5050-chip', 'Vakum Nozzle modeli: 501, 502, 503, 504, 505', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/348/id/306.html', ''),
(61, 4, 'Automatski-dodaci', 'Nečujan Air Kompresor (Oil-free)', 0, 'Necujan-Air-Kompresor-Oil-free', 'KAYO', 'Compressor.jpg', 'New generation of mechatronics product, No lubrication is needed,  Silent ball bearing copper wire motor, The voice of machine under running is around 65dB', 'New generation of mechatronics product, no lubrication is needed, which makes the generated air clearer and more environmental friendly, and also greatly reduces the air compressor maintenance costs. Silent ball bearing copper wire motor, durable, long service life, long-term working without burning machine. High performance heat dissipation system, effectively reduces the head temperature, to protect the head long-term use without burned. China Energy Efficiency Level 1, very energy saving.', 0, 'http://en.kayosmt.com/index.php/Show/index/cid/348/id/313.html', ''),
(62, 2, 'Desktop-peći', 'Desktop peć FT04', 0, 'Desktop-pec-FT04', 'C.I.F', 'FT04.jpg', 'Daljinsko upravljanje pećnicom zahvaljujući Android ™ aplikacijom i Bluetooth® , Grejni elementi: 4 x 1000W grejač, Max. temp.: 50 - 260°C, Radna površina: 220 x 320mm, Hladjenje PCB-a nakon procesa grejanja, Memorija za 98 profila', 'Daljinsko upravljanje pećnicom FT04 zahvaljujući Android ™ aplikaciji i Bluetooth® tehnologiji. Android ™ tablet se standardno isporučuje sa aplikacijom za kontrolu pećnice. Rad na visokoj temperaturi za olovni i bezolovni kalaj. Mogućnost memorisanja 98 profila. Kontrola temperature sa mikroprocesorom. Prikaz procesa na LCD monitoru: temperatura i vreme. Uključen je i režim hladjenja.', 0, 'https://cif.fr/en/batch-reflow-ovens/444-four-de-refusion-a-convection-forcee-ft-03.html', ''),
(63, 2, 'Desktop-peći', 'Desktop peć FT03', 0, 'Desktop-pec-FT03', 'C.I.F', 'FT031.jpg', 'Grejači: 2 nivoa, Regulacija temp. sa mikroprocesorom, Max. temp.: 300°C, Radna površina: 190 x 290mm, Kvarcni grejači: 2 x 1KW, Vreme procesa u pećnici: oko 3min, Mogućnost memorisanja 10 profila, Displej za praćenje procesa profila', 'FT03 pećnica je odlična za prototipne PCB ploče. Rad na visokoj temperaturi za olovni i bezolovni kalaj. U liniji uključuje mnoge funkcije kao što je memorisanje 10 profila, prikaz informacija na LCD monitoru, prozor za nadgledanje procesa. Kontrola temperature sa mikroprocesorom, max. T° 300°C. Digitalni prikaz procesa: temperatura i vreme. Jednostavno programiranje za neposrednu kontrolu.', 0, 'https://cif.fr/en/batch-reflow-ovens/385-four-de-refusion-a-convection-forcee-ft-03.html', ''),
(64, 2, 'Desktop-peći', 'Desktop peć FT06-SA', 0, 'Desktop-pec-FT06-SA', 'C.I.F', 'FT06.jpg', 'Grejači: 2 nivoa, Grejni elementi: 8 x lampe 1000W; 1 x grejač 2200W, Max. temp.: 50 - 260°C, Radna površina: 380 x 250mm, Regulacija temp. sa mikroprocesorom, Hladjenje PCB-a nakon procesa grejanja, Mogućnost rada pod azotom (N2), Memorija za 98 profila', 'FT06-SA je profesionalna pećnica nove generacije. Rad na visokoj temperaturi za olovni i bezolovni kalaj. Mogućnost memorisanja 98 profila uz praćenje na LCD displeju. Pećnica FT06-SA dizajnirana je kao autonomni uređaj. Automatsko otvaranje i zatvaranje pećnice. Nakon završetka procesa u pećnici vrata se otvaraju i započinje proces hladjenja. Programsko profilisanje procesa je jednostavno pomoću standardne PC tastature spojene na pećnicu. Na prednjoj delu pećnice imate dva LCD ekrana za proveru stanja pećnice i temperature. Ako povežete termopar, možete da izmerite tačnu temperaturu na PCB-u. Može da radi pod azotom (N2), priključuje se na zadnjoj strani pećnice.', 0, 'https://cif.fr/en/batch-reflow-ovens/330-four-de-refusion-a-convection-forcee-ft-05.html', ''),
(65, 2, 'Desktop-peći', 'Desktop peć FT05.B', 0, 'Desktop-pec-FT05B', 'C.I.F', 'FT05B.jpg', 'Grejači: 2 nivoa, Regulacija temp. sa mikroprocesorom, Max. temp.:  300°C, Radna površina: 350 x 400mm, Kvarcni grejači: 4 x 1KW, Vreme procesa u pećnici: oko 5min, Set od 3 Termopar K za kontrolu temperature, Mogućnost memorisanja 10 profila', 'FT05.B je profesionalna pećnica nove generacije. Rad na visokoj temperaturi za olovni i bezolovni kalaj.  Mogućnost memorisanja 10 profila uz praćenje na LCD displeju. 4 priključka na prednoj strani: 3 za Termopare i 1 za računar. Pećnica FT05.B kompatibilna je sa softverom SMTik-FT®. U režimu «Test»: ovaj softver podešava pećnicu za testiranje profila na PCB ploči, za pregled praćenja profila, za validnost testova i za memorisanje 10 različitih profila u pećnici ili u računaru. U režimu «Proizvodnja»: aktivacija pećnice na osnovu valjanih i memorisanih testova. Sigurnost: dvostruko staklo sa cirkulacijom vazduha, zaključavanje ulaznih vrata, odvodna cev za isparenje lemnog dima. OPCIONO: Sistem za izvlačenje isparenja (lemnog dima). Softver SMTik-FT: kompatibilan sa verzija Windows® XP, Vista, 7 i 8. Lako programiranje za jednostavnu upotrebu.', 0, 'https://cif.fr/en/batch-reflow-ovens/123-four-de-refusion-a-convection-forcee-ft-05.html', ''),
(66, 2, 'Manualni-polagač', 'Polu-automatski P&P EXPERT RANGE', 0, 'Polu-automatski-PP-EXPERT-RANGE', 'C.I.F', 'poluautomatik1.jpg', 'Sistem za brzu izradu prototipnih PCB ploča, Min. radna površina: 25 x 25mm, Max radna površina: 425 x 253mm, Komponente: 0402 - BGA; 0201 uz mikro kameru (opciono), Brzina postavljanja komponenti: 400 - 600cph, Sistem za postavljanje: BGA; CSP; Flip Chip', 'Polu-automatski P&P - EXPERT RANGE dizajniran je za brzu izradu prototipa i proizvodnju malih serija. Integrisani sistem za doziranje kalajne paste i alat za topli vazduha čine ovu mašinu svestranim, ali kompaktnim proizvodnim uredjajem. Dostupan u 4 različita modela u manualnoj ili poluautomatskoj verziji i mnoge mogućnosti se mogu prilagoditi. U FINEPTICH verziji će vam omogućiti da precizno postavite BGA i QFN komponente. Precizno podešavanje x, y i t ose. Automatsko spuštanje komponenata na PCB. Mikroprocesorska kontrola sa LCD-om. OPCIONO:  1. Kartica za podršku sa mikrometrijskim pozicioniranjem.  2. Instalacioni softver.  3. Dozator za lemnu pastu i lepak.  4. Mikro kamera.  5. Mikropolagač sistem za BGA, mBGA i QFP.  6. Stanica za topli vazduh. ', 0, 'https://cif.fr/en/semi-automatic-smd-manipulators/257-station-de-placement-manuel-professionnel-precitec.html', ''),
(67, 2, 'Manualni-printeri', 'Manualni štampač za SMD - TECPRINT 700', 0, 'Manualni-stampac-za-SMD-TECPRINT-700', 'C.I.F', 'stampac.jpg', 'Fiksiranje šablona različitih formata, Maksimalna veličina PCB: 300 x 400mm, Minimalna veličina PCB: 30 x 50mm, Maksimalna veličina šablona: 310 x 470mm, Minimalna dimenzija šablona: 50 x 50mm, Veoma lako poravnavanje u X; Y i theta ± 7,0 mm ose', 'TECPRINT 700 je novi manualni štampač za postavljanje kalajne paste. Ova kompaktna mašina omogućava vam da tačno nanesete lemnu pastu. Šablon se postavlja u sekundi zahvaljujući originalnom sistemu samozatezajućeg okvira. Nema potrebe da imate okvir za svaki šablon. Poravnavanje X,Y i theta ose vrši se sa 3 šrafa na bočnim stranama mašine. Uz manualni štampač se isporučuje metalna lopatica (špahla) za nanošenje i ravnanje kalajne paste od nerdjajućeg čelika i 3 podesive igle (podupirači) za PCB protiv savijanja same PCB ploče.', 0, 'https://cif.fr/en/manual-operated-stencil-printer-for-smd/292-manual-operated-stencil-printer-for-smd-tecprint-700.html', ''),
(68, 2, 'Manualni-printeri', 'Manualni štampač za SMD - TECPRINT 500', 0, 'Manualni-stampac-za-SMD-TECPRINT-500', 'C.I.F', 'stampac1.jpg', 'Fiksiranje šablona različitih formata, Maksimalna veličina PCB: 200 x 270mm, Minimalna veličina PCB: 30 x 50mm, Maksimalna veličina šablona: 210 x 320mm, Minimalna dimenzija šablona: 50 x 50mm, Veoma lako poravnavanje u X; Y i theta ± 7,0 mm ose', 'TECPRINT 500 je novi manualni štampač za postavljanje kalajne paste. Ova kompaktna mašina omogućava vam da tačno nanesete lemnu pastu. Šablon se postavlja u sekundi zahvaljujući originalnom sistemu samozatezajućeg okvira. Nema potrebe da imate okvir za svaki šablon. Poravnavanje X,Y i theta ose vrši se sa 3 šrafa na bočnim stranama mašine. Uz manualni štampač se isporučuje metalna lopatica (špahla) za nanošenje i ravnanje kalajne paste od nerdjajućeg čelika i 3 podesive igle (podupirači) za PCB protiv savijanja same PCB ploče.', 0, 'https://cif.fr/en/manual-operated-stencil-printer-for-smd/285-manual-operated-stencil-printer-for-smd-tecprint-500.html', ''),
(70, 2, 'Manualni-polagač', 'Manualni SMD polagač PRECITEC.ELITE', 0, 'Manualni-SMD-polagac-PRECITECELITE', 'C.I.F', 'cif1.jpg', 'Sistem za postavljanje SMT komponenti, Rad sa obe ruke,  Radna površina: 350 x 400mm, Komponente: od 0402 - QFP, Brzina postavljanja komponenti: do 900 cph, Dozer za kaljnu pastu, Kutije za odlaganje SMD-a - 12 kom, Fideri i kolor kamera (opciono)', 'Manualni SMD polagač PRECITEC.ELITE je sistem za postavljanje SMT komponenti. To je savršena ergonomska stanica koja uključuje puno funkcija sa atraktivnom cenom. Može da se koristi sa obe ruke istovremeno bez promene konfiguracije. Lagano kretanje rukama u osi X,Y omogućava udoban izbor komponenti i njihovo postavljanje po celom radnoj površini. Komponente takođe možete lako okretati za 360 °. Magnetni nosači za PCB ploče. Vakuum pumpa integrisana u sklopu jedinice. Efikasno osvetljenje ugrađeno u ručku. Držač za špriceve za doziranje paste i lepka. OPCIONO:  1. Kolor kamera sa USB konekcijom.  2. Fider za trake za montažu (3 x 8mm ; 1 x 12mm ; 1 x 16mm).', 0, 'https://cif.fr/en/manual-pick-place-stations/401-high-accuracy-smd-manipulator-precitecelite.html', ''),
(71, 2, 'Manualni-polagač', 'Manualni SMD polagač  EAYSYPLACER.V', 0, 'Manualni-SMD-polagac-EAYSYPLACERV', 'C.I.F', 'eaysyplacer-v-trnas.png', 'Sistem za postavljanje SMT komponenti, Radna površina: 380 x 240mm, Kamera u boji + TFT LCD monitor od 9 \", Komponente: od 0402 - QFP, Brzina postavljanja komponenti: do 900 cph, Vakum pumpa; 2 igle; 3 nosača ploče, Fideri (opciono)', 'Manualni SMD polagač EAYSYPLACER.V je sistem za postavljanje SMT komponenti. To je savršena ergonomska stanica koja uključuje puno funkcija sa atraktivnom cenom. Lagano kretanje rukom u osi X,Y omogućava udoban izbor komponenti i njihovo postavljanje po celom radnoj površini. Komponente takođe možete lako okretati za 360 °. Kamera koja se nalazi u blizini vakumske pipete je povezana sa monitorom i pomaže oprateru u postavljanju sitnih komponenti. Efikasno osvetljenje ugrađeno u ručku. OPCIONO: 1. Univerzalni fider za 10 traka od 8mm  2. Držač za 10 rilova. 3. Standardnai fider za 5 stikova - ICs S08.  4. Standardnai fider za 5 stikova - ICs S16.  5. Dozer za kalajnu pastu.', 1, 'https://cif.fr/en/manual-pick-place-stations/332-hand-operated-smt-assembly-manipulator-with-video-eaysyplacer-v.html', ''),
(72, 5, 'Mikroskopi', 'Video Mikroskop SANXO-Scope HD U3', 0, 'Video-Mikroskop-SANXO-Scope-HD-U3', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', 'It is built with an IDS Imaging 5MPixel camera, New much faster focus approach by applying the focusing method on the map, The tunable lens adds features for the use, ', 'The digital video-microscopes conceived by Sanxo offers a complete configuration with a close-up high quality image in direct inspection. The Sanxo-scope U3 produces a frame rate from 38 to 62 FPS. It was initially conceived as a manual inspection workshop for electronic cards. It is robust, accessible and can be used for any other object.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/411-digital-microscopes-hd-sanxo.html', ''),
(73, 5, 'Mikroskopi', 'Video Mikroskop SANXO-scope HD U4 Express', 0, 'Video-Mikroskop-SANXO-scope-HD-U4-Express', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', 'Build with  an IDS Imaging 18MPixel camera, The tunable lens adds features for the user, New much faster focus approach by applying the focusing method on the map, The focus is done in a couple of milliseconds', 'Range of digital video-microscopes conceived by Sanxo that offers a complete configuration with a close-up high quality image in direct inspection. They produce a frame rate from 35 to 62 FPS for the Sanxo-scope HD U4 and from 45 to 70 FPS for the Sanxo-scope HD U4 Express.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/412-digital-microscopes-hd-sanxo.html', ''),
(74, 5, 'Mikroskopi', 'Video Mikroskop SANXO-SCOPE HD U5 HYPER', 0, 'Video-Mikroskop-SANXO-SCOPE-HD-U5-HYPER', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', 'DIGITAL MICROSCOPE HD, Built with an IDS Imaging 2.3MPixel camera, The tunable lens adds features for the use, 100-150 FPS, ', 'The digital video-microscopes conceived by Sanxo offers a complete configuration with a close-up high quality image in direct inspection. The Sanxo-scope U5 hyper produces a frame rate from 100 to 150 fps. It was initially conceived as a manual inspection workshop for electronic cards. It is robust, accessible and can be used for any other object.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/414-digital-microscopes-hd-sanxo.html', ''),
(75, 5, 'Mikroskopi', 'Video Mikroskop SANXO-SCOPE HD U6', 0, 'Video-Mikroskop-SANXO-SCOPE-HD-U6', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', 'It is built with an IDS Imaging 3.1MPixel camera, The tunable lens adds features for the user, The focus is done in a couple of milliseconds', 'Therefor a 3D imaging of the surface is generated to give a better understanding and a clear visualization of the object. The digital video-microscopes conceived by Sanxo offers a complete configuration with a close-up high quality image in direct inspection. The Sanxo-scope U6 produces a frame rate from 57 to 80 FPS.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/415-digital-microscopes-hd-sanxo.html', '');
INSERT INTO `product` (`id`, `categories_id`, `subcategory`, `title`, `rb`, `slug`, `proizvodjac`, `product_image`, `karakteristike`, `opis`, `preporucujemo`, `url`, `sizes`) VALUES
(76, 5, 'Mikroskopi', 'Video Mikroskop SANXO-SCOPE HD U4 VALUE', 0, 'Video-Mikroskop-SANXO-SCOPE-HD-U4-VALUE', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', '18 MPIXEL, 30 TO 58 FPS, The tunable lens adds features for the user, The use of the stacking Pictures method and the HDR ', 'The digital video-microscopes conceived by Sanxo offers a complete configuration with a close-up high quality image in direct inspection. The Sanxo-scope HD U4 value produces a frame rate from 30 to 58 fps. it was initially conceived as a manual inspection workshop for electronic cards; it is robust, accessible and can be used for any other object.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/416-digital-microscopes-hd-sanxo.html', ''),
(77, 5, 'Mikroskopi', 'Video Mikroskop SANXO-SCOPE DUAL - 2 X ', 0, 'Video-Mikroskop-SANXO-SCOPE-DUAL-2-X', 'C.I.F', 'digital-microscopes-hd-sanxo.jpg', 'It is built with two IDS Imaging 18 MPixel cameras, 25 - 60 FPS, 	\r\nMegapixel TAMRON 50 or 25 mm, INTEL NUC i7® 8GB RAM, 256 GB SSD   ', 'The digital video-microscopes conceived by Sanxo offers a complete configuration with a close-up high quality image in direct inspection. The Sanxo-scope DUAL produces a frame rate from 25 to 60 FPS. It was initially conceived as a manual inspection workshop for electronic cards. It is robust, accessible and can be used for any other object.', 0, 'https://cif.fr/en/digital-microscopes-hd-sanxo/456-digital-microscopes-hd-sanxo.html', ''),
(78, 3, 'Isparenja', 'Sistem za izvlačenje isparenja FILTRATEC-A', 0, 'Sistem-za-izvlacenje-isparenja-FILTRATEC-A', 'C.I.F', 'filtratec-a.jpg', 'Veoma tih <52 dbA, HEPA filter (standard), On / off Daljinsko upravljanje (standard), Snaga turbine 255 m3 / h, Povezivanje sa usisnim crevom, Mogućnost korišćenja dva creva', 'FILTRATEC-a je stanica za uvlačenje dima pri lemljenju komponenti u elektronici, isprenja u hemijskoj i mašinskoj industriji. Svaka stanica standardno poseduje HEPA + Neutrafil filter, 2 brzine, moćnu turbinu i vrlo tihu (<52 dB). Bežični daljinski upravljač (uključen / isključen) je standardno. Jednostavno povezivanje sa fleksibilnim usisnim crevom. Mogućnost korišćenja dva creva za dva radna mesta.', 0, 'https://cif.fr/en/the-filtratec-autonomous-filtration-units/177-filtratec-f.html', ''),
(79, 3, 'Isparenja', 'Sistem za izvlačenja isparenja FILTRATEC-F', 0, 'Sistem-za-izvlacenja-isparenja-FILTRATEC-F', 'C.I.F', 'filtratec-f.jpg', 'Veoma tih <52 dbA, HEPA filter (standard), On / off Daljinsko upravljanje (standard), Snaga turbine 255 m3 / h, Povezivanje sa usisnim crevom, Mogućnost korišćenja dva creva', 'FILTRATEC-F je stanica za uvlačenje dima pri lemljenju komponenti u elektronici i isprenja u hemijskoj industriji. Svaka stanica standardno poseduje HEPA + Neutrafil filter, 2 brzine, moćnu turbinu i vrlo tihu (<52 dB). Bežični daljinski upravljač (uključen / isključen) je standardno. Jednostavno povezivanje sa fleksibilnim usisnim crevom. Mogućnost korišćenja dva creva za dva radna mesta.\r\n', 0, 'https://cif.fr/en/the-filtratec-autonomous-filtration-units/178-filtratec-a.html', ''),
(80, 3, 'Isparenja', 'Sistem za izvlačenja isparenja TMT-FE100S + FE-KIT-1', 0, 'Sistem-za-izvlacenja-isparenja-TMT-FE100S-FE-KIT-1', 'Thermaltronics', 'Fume1.jpg', ' HEPA filtration ensuring operator safety, Light & compact, takes up minimal benchtop space, Adjustable, easy to use fan speed control', 'The Thermaltronics TMT-FE100S fume extraction unit, takes up minimal benchtop space but is inclusive of a prefilter and a separate HEPA filter, to ensure operator safety. Fan speed can also be adjusted, based on the proximity of the soldering operation or the amount of fumes being generated.', 0, 'http://www.thermaltronics.com/tmt-fe100s.php', ''),
(81, 6, 'Robot-lemljenje', 'Robot za lemljenje TMT-R9800S', 0, 'Robot-za-lemljenje-TMT-R9800S', 'Thermaltronics', 'tmt-r9800s.jpg', 'Dual Arm, Six Axis Soldering Robot, Intelligently compensates for PCBA variance, Image Recognition & Mapping System, Laser Height Measurement, Uses Curie Heat Technology for precise temperature control', 'The Thermaltronics Robotic System incorporates innovative design concepts and precision components to ensure accuracy. The combination of high precision hardware and intelligent software ensures precision soldering and low operator training costs.', 1, 'http://www.thermaltronics.com/tmt-r9800s.php', ''),
(82, 5, 'Mikroskopi', 'HDMI Video Mikroskop (Full HD)', 0, 'HDMI-Video-Mikroskop-Full-HD', 'Pro-Tech', 'mikroskop.jpg', 'Dobar radni razmak: 4cm - 15cm, Uvećanje od 10 do 300 puta ; 1920x1080P, Senzor slike: 3 megapiksela, Video izlaz: 1080p Full HD (HDMI), Format video zapisa: MOV, Format fotografije: JPEG, Skladištenje: MicroSD kartica do 32G (NIJE uključena), 5V DC', 'Karakteristike: Dobar radni razmak: 4cm - 15cm / Ekskluzivna sočiva: smanjuju prigušeni odsjaj i sprečavaju štetu od mrlja koje nastaju procesom lemljenja / Slike u realnom vremenu, bez mrlja / Uvećanje: od 10 do 300 puta, 1920 x 1080P, 30 kadrova u sekundi visokog kvaliteta / Digitalni zum: 4x / Metalno postolje, čvrsto i izdržljivo, 2 fleksibilne lampe za osvetljenje / Senzor slike: 3 megapiksela / Video izlaz: 1080p Full HD / Format video zapisa: MOV / Format fotografije: JPEG / Opseg fokusa: Ručni fokus od 10 mm do 500 mm / Brzina kadrova: max 30 f/s / Odnos uvećanja: 10x do 300x / Interfejs za video izlaz: HDMI, za bilo koji monitor sa HDMI ulazom / Skladištenje: MicroSD kartica, do 32G (NIJE uključena) / Izvor napajanja: 5V DC', 1, '', ''),
(85, 7, 'Podovi', 'Antistatički dupli podovi', 0, 'Antistaticki-dupli-podovi', 'Tarkett', 'dupli-pod.jpg', 'Antistatički, Izdržljivi, Lako se održavaju, Sprečavaju klizanje', 'Moguće podesavati visinu duplih podova.', 0, 'http://linea-plus.rs/delatnosti/', ''),
(86, 7, 'Podovi', 'PVC podovi', 0, 'PVC-podovi', 'Tarkett', 'pvc-pod.jpg', 'Veliki izbor dezena, Kvalitetni i izdržljivi, Laki za održavanje', 'Sve podove ugrađujemo vrlo brzo i kvalitetno.', 0, 'http://linea-plus.rs/delatnosti/', ''),
(87, 1, 'Lemilice', 'Lemilica TMT-2000S', 2, 'Lemilica-TMT-2000S', 'Thermaltronics', 'TMT-2000S.jpg', 'Curie Heat Technologija koji radi na 470KHz, Dva izlaza za rad, Mogućnost korišćenja tri različite serije vrhova ( K; P; S serije), Izuzetno kompaktan; težina svega 1.3 kg, Nije potrebna kalibracija ili obuka operatera, Snaga: 50W', 'Lemilica TMT-2000S zasnovana je na tehnologiji Curie Heat koja reaguje na toplotne potrebe svakog lemnog spoja. Samopodešavanjem snage (toplote) ispunjava tačni zahtev komponente i materijala za lemljenje na PCB ploči. Brzina dostizanja snage (temperature) za rad je oko 5 sekundi. Na samoj stanici moguće je priključiti razlemljivač (pištolj) i termo pincetu. Postoji mogućnost naizmeničnog rada na stanici za dve različite aplikacije.  - Opširnije informacije za razlemljivač (pištolj) i termo pincete možete videti u podkategoriji \"Propratna oprema i materijal\"- Izbor vrhova iz Serije K, P i S mozete videti na \"Detaljnije na sajtu proizvođača\"\r\n', 0, 'http://www.thermaltronics.com/tmt-2000s.php', ''),
(89, 7, 'Odeća', 'Antistatički mantili', 0, 'Antistaticki-mantili', 'Pro-Tech', 'belimantil.png', 'Tip: Zaštitni mantil; antistatik; ESD, Sastav: 32.8% pamuk; 66.6% poliester; 0.6% ugljenično vlakno, Kroj: ženski/muški, Džepovi: dva na dnu i  jedan sa leve strane grudi, ESD znak: mesto po izboru klijenta, Logo klijenta: vez / štampa (opciono)', 'Antistatička mantil je napravljena od statičnog disipativnog materijala za korišćenje u ESD zaštićenim prostorijama. Mantili su lagani, udobni i mogu se prati u veš mašinama. Otpornost u skladu sa standardom PN-EN 61340-5-1', 1, '', ''),
(90, 7, 'Odeća', 'Antistatičke POLO majice', 0, 'Antistaticke-POLO-majice', 'Pro-Tech', 'zelenamajica.png', 'Tip: zaštitna majica; antistatik; ESD, Sastav: 96% pamuk; 4% ugljenično vlakno, Kroj: ženski/muški,  Veličine: 3XS do 3XL, Džepovi: jedan sa leve strane grudi, ESD znak: mesto po izboru klijenta, Logo klijenta: vez / štampa (opciono)', 'Antistatička polo majica je napravljena od statičnog disipativnog materijala za korišćenje u ESD zaštićenim prostorijama. One su lagane, udobne i mogu se prati u veš mašinama. Otpornost u skladu sa standardom PN-EN 61340-5-1', 1, '', ''),
(92, 1, 'Stanica-vazduh', 'Mlaznice za stanice za topli vazduh', 0, 'Mlaznice-za-stanice-za-topli-vazduh', 'Thermaltronics', 'nozle2.jpg', 'Različiti tipovi mlaznica, BGA; BQFP; PLCC; QFP, SOIC; SOJ; SOL; TSOP', 'Različiti tipovi i dimenzija mlaznica za dršku stanice za topli vazduh. Ove mlaznice se nazivaju \"otvorenim\" jer topao vazduh izlazi iz njih kroz specijalne vazdušne prolaze.', 0, 'http://www.thermaltronics.com/htn_series.php', ''),
(93, 6, 'Stanica-vazduh', 'Stanica za topli vazduh TMT-HA600', 0, 'Stanica-za-topli-vazduh-TMT-HA600', 'Thermaltronics', 'ha600.jpg', 'Brzo povećanje i spuštanje temperature, Digitalni displej, Jednostavno podešavanje temperature i protoka vazduha, Veliki izbor visokokvalitetnih mlaznica, Snaga:1300W', 'Stanica za topli vazduh TMT-HA600 koristi veliku membransku pumpu i grejač velike snage 1300W. Dizajniran za rad na težim aplikacijama za demontažu / montažu komponenti na PCB pločama. Uz stanicu se dobijaju mlaznice (5.0mm,  8.0mm, 10.0mm, 12.0mm)', 0, 'http://www.thermaltronics.com/tmt-ha600.php', ''),
(94, 6, 'Stanica-vazduh', 'Stanica za topli vazduh TMT- HA300', 0, 'Stanica-za-topli-vazduh-TMT-HA300', 'Thermaltronics', 'ha300.jpg', 'Digitalni displej prikazuje temperaturu i status, Merač protoka vazduha omogućava povratnu informaciju,  Podesivi tasteri za kontrolu temperature i vazduha, Veliki izbor visokokvalitetnih mlaznica, Snaga: 500W', 'Stanica za topli vazduh TMT-HA300 koristi veliku membransku pumpu i može se koristiti za za demontažu / montažu komponenti SOIC, CHIP, KFP, PLCC i druge na PCB pločama. Uz stanicu se dobijaju mlaznice (3.0mm, 5.0mm, 8.0mm, 10.0mm)', 0, 'http://www.thermaltronics.com/tmt-ha300.php', ''),
(95, 6, 'Stanica-vazduh', 'Stanica za topli vazduh TMT- HA200', 0, 'Stanica-za-topli-vazduh-TMT-HA200', 'Thermaltronics', 'ha200.jpg', 'Automatski \"sleep mode\" kada se postavi na držač, Podesivi tasteri za kontrolu temperature i vazduha, Lagan i kompaktan, Veliki izbor visokokvalitetnih mlaznica, Snaga: 600w', 'Stanica za topli vazduh TMT-HA200  se koristiti za za demontažu / montažu komponenti SOIC, CHIP, KFP, PLCC i druge na PCB pločama. Uz stanicu se dobijaju mlaznice (3.0mm, 5.0mm, 8.0mm, 10.0mm)', 0, 'http://www.thermaltronics.com/tmt-ha200.php', ''),
(96, 1, 'Stanica-vazduh', 'Stanica za topli vazduh TMT- HA100', 0, 'Stanica-za-topli-vazduh-TMT-HA100', 'Thermaltronics', 'ha100.jpg', ' Specijalizovani za rad na malim komponentama, Koristi HAP serije mlaznice za olovku sa vrućim vazduhom, Visokokvalitetni grejni element, Obezbeđuje brzo i dugotrajno grejanja, Snaga: 200W', 'Stanica za topli vazduh TMT-HA100 dizajnirana je za demontažu / montažu malih preciznih komponenti na PCB pločama. Uz stanicu se dobijaju HAP mlaznice (1.5mm, 2.0mm, 2.5mm, 3.0mm, 3.5mm, 4.0mm)', 0, 'http://www.thermaltronics.com/tmt-ha100.php', ''),
(97, 1, 'Stanica-vazduh', 'Ručka (stanica) za topli vazduh TMT-HA050', 0, 'Rucka-stanica-za-topli-vazduh-TMT-HA050', 'Thermaltronics', 'ha050.jpg', 'Stanica integrisana u ručku za topli vazduh, Digitalni displej prikazuje temperaturu i protok vazduha, Lagan; prenosiv i jednostavan za korišćenje, Koristi mlaznice iz serije HTN, Snaga: 600W', 'Ručka (stanica) za topli vazduh TMT-HA050 koristiti se za za demontažu / montažu komponenti SOIC, QFP, PLCC i drugih na PCB pločama. Uz stanicu se dobijaju mlaznice (3.0mm, 5.0mm, 8.0mm, 10.0mm)', 0, 'http://www.thermaltronics.com/tmt-ha050.php', ''),
(100, 1, 'Predgrejači', 'PCB Predgrejač TMT-PH600', 0, 'PCB-Predgrejac-TMT-PH600', 'Thermaltronics', 'ph600.jpg', 'Mikroprocesor precizno reguliše temperaturu, Tri načina predgrevanja kako bi se zadovoljili različiti zahtevi za lemljenje, Profesionalni držač PCB ploče, Veliki IC grejni element, Dve sonde za spoljnu temperaturu,  Snaga: 1500W, Radna površina: 310mmx310', 'PCB predgrejač TMT-PH600 koristi naprednu inteligentnu tehnologiju za kontrolu temperature na infracrvenim grejačima. Tri načina grejanja omogućavaju uređaju da upravlja predgrevanjem kalaja sa i bez olova na PCB ploči. Pogodni su za upotrebu PCB ploča koji sadrže različite veličine SMD komponenti.', 0, 'http://www.thermaltronics.com/tmt-ph600.php', ''),
(101, 1, 'Predgrejači', 'PCB Predgrejač TMT-PH300', 0, 'PCB-Predgrejac-TMT-PH300', 'Thermaltronics', 'ph300.jpg', 'Mikroprocesor precizno reguliše temperaturu, Tri načina predgrevanja kako bi se zadovoljili različiti zahtevi za lemljenje, Profesionalni držač PCB ploče, Veliki IC grejni element, Dve sonde za spoljnu temperaturu, Snaga: 850W, Radna površina: 200mm x 250', 'PCB Predgrejač TMT-PH300 koristi naprednu inteligentnu tehnologiju za kontrolu temperature na infracrvenim grejačima. Tri načina grejanja omogućavaju uređaju da upravlja predgrevanjem kalaja sa i bez olova na PCB ploči. Pogodni su za upotrebu PCB ploča koji sadrže komponente BGA i SMD.', 0, 'http://www.thermaltronics.com/tmt-ph300.php', ''),
(102, 1, 'Predgrejači', 'PCB Predgrejač TMT-PH200', 0, 'PCB-Predgrejac-TMT-PH200', 'Thermaltronics', 'ph200.jpg', 'Senzor kontroler za kontrolu temperature, Podesivi taster za regulaciju temperature, Digitalni displej za prikazivanje temperaturu, IC grejni element, Snaga: 600W, Radna površina: 130mm x 130mm', 'PCB Predgrejač TMT-PH200 je senzorski kontroler za kontrolu temperature na infracrvenim grejačima. Pogodan je za proces predgrevanja kalaja sa i bez olova na PCB ploči. Idealan za manje tipove PCB ploča.', 0, 'http://www.thermaltronics.com/tmt-ph200.php', ''),
(103, 1, 'Propratni-materijal', 'Termo pinceta TZ-KIT komplet', 1, 'Termo-pinceta-TZ-KIT-komplet', 'Thermaltronics', 'pinceta.jpg', 'Korišćenje vrhova za pincetu iz TZ Serije, Dizajnirano za demontažu većine SMD komponenata, Podesivo poravnavanje vrhova u x-y smerovima, Mogućnost priključenja na svim TMT stanicama', 'Termo pinceta TZ-KIT držač pinceta ergonomski je dizajniran za obradu čak i najmanjih komponenti. Omogućava zaključavanje obe ručke i podešavanje vrhova vodoravno i vertikalno. Moze da se priključi na sve TMT stanice. Izbor vrhova iz Serije TZ mozete videti \" na \"Detaljnije na sajtu proizvođača\"', 0, 'http://www.thermaltronics.com/tz-kit-1.php', ''),
(104, 1, 'Propratni-materijal', 'Razlemljivač (pištolj) DS-KIT komplet', 2, 'Razlemljivac-pistolj-DS-KIT-komplet', 'Thermaltronics', 'pistolj.jpg', 'Demontaža \"thru-hole\" komponenata, Visok termički oporavak i performanse, Jednostavno i lako za održavanje, Mogućnost priključenja na svim TMT stanicama', 'Razlemljivač (pištolj) DS-KIT je komplet za odlemljivanje svih \"thru-hole\" komponenata. Koristi se externi kompresor (4-6 bara) kako bi stvorio snažan vakuum za skidanje kalaja sa \"thru-hole\" komponenata . Čišćenje i održavanje je brzo i jednostavno. Moze da se priključi na sve TMT stanice. Izbor vrhova iz Serije DT mozete videti \" na \"Detaljnije na sajtu proizvođača\"', 0, 'http://www.thermaltronics.com/m_desolder_gun.php', ''),
(105, 7, 'Mikroskopi', 'Čigra', 444, 'Čigra', 'Kayo', 'php.png', 'ssss', 'sssss', 1, '', ''),
(106, 7, 'Mikroskopi', 'Čačak', 44, 'Čačak', 'Kayo', 'android.png', 'hgfhfhgfh', 'sdasdasdas', 1, '', ''),
(107, 4, 'Peći-lemljenje', 'ČigraČĆšš', 157, 'ČigraČĆšš', 'Kayo', 'androidstudio.png', 'vhvhjvghj', 'zhuggzutguz', 1, '', ''),
(108, 7, 'Mikroskopi', 'Čigraćšć', 1574, 'Čigraćšć', 'Kayo', 'github.png', 'asdadas', 'sdadas', 1, '', ''),
(109, 7, 'Peći-lemljenje', 'Čigra nova', 343534, 'Čigra-nova', 'gdsfdsfds', 'java.png', 'dfdsfds', 'sdfdsfds', 1, '', ''),
(110, 7, 'Peći-lemljenje', 'Čigra bbbf', 3435, 'Čigra-bbbf', 'jk', 'android.png', 'sdas', 'sdas', 1, '', ''),
(111, 7, 'Peći-lemljenje', 'Čigra antistatočka', 343322, 'Cigra-antistatocka', 'dfdd', 'github.png', 'dfdssdfds', 'dsfsfds', 1, '', ''),
(112, 6, 'df', 'Izmenjeni', 2147483647, 'Izmenjeni', 'dfd', 'testy.jpg', 'izmena', 'fdfd', 1, '', 'testy.jpg'),
(113, 7, 'Peći-lemljenje', 'Čihndkf Šksjbđž', 77777, 'Čihndkf-Šksjbđž', 'Kayo', 'css.png', 'fdf', 'dfdfd', 1, '', ''),
(114, 7, 'Automatski-dodaci', 'Čihndkf Šksjbđž', 88888888, 'Čihndkf-Šksjbđž', 'Kayo', 'androidstudio.png', 'dssssss', 'sdsds', 1, '', ''),
(115, 7, 'Mikroskopi', 'Čihndkf Šksjbđž', 2147483647, 'Cihndkf-Sksjbdjz', 'Kayo', 'bootstrap.png', 'sdsdsd', 'sdssds', 1, '', ''),
(116, 4, 'Peći-lemljenje', 'Čihndkf Šksjbđž', 2147483647, 'Cihndkf-Sksjbdjz', 'C.I.F', 'nodejs.png', 'sdsvfdvd', 'dsdss', 1, '', ''),
(125, 6, 'Antistatik podloge', 'Majica muska 22', 908, 'Majica-muska-22', 'Kayo', 'testy.jpg', 'tfafsf', 'tafafas', 0, 'http://protech-servis.rs/', 'testy.jpg'),
(126, 7, 'Antistatik podloge', 'Majica muska', 86666, 'Majica-muska', 'Kayo', 'testy.gif', 'htt', 'htth', 1, 'http://protech-servis.rs/', 'testy.gif'),
(127, 6, 'Antistatik podloge', 'Majica muskafffff', 157134667, 'Majica-muskafffff', 'Kayo', 'testy.jpg', 'jukkhj', 'ghghg', 0, 'http://protech-servis.rs/', '');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin NOT NULL,
  `username` varchar(255) COLLATE utf8_bin NOT NULL,
  `password` varchar(255) COLLATE utf8_bin NOT NULL,
  `email` varchar(255) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `username`, `password`, `email`) VALUES
(1, 'ddd', 'ddd', 'ddd', 'ddd'),
(2, 'ddd', 'ddd', 'ddd', 'ddd'),
(3, 'dova', 'dova', '3afbd99bc2a514308d4cce6e3a83c3b0', 'dova@gmail.com');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `product`
--
ALTER TABLE `product`
  ADD CONSTRAINT `product_ibfk_1` FOREIGN KEY (`categories_id`) REFERENCES `categories` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
